function analysis = analyze_task8_h1b_cpbar_readonly(options)
%ANALYZE_TASK8_H1B_CPBar_READONLY Fixed-evidence offline H1b experiment.
%   Scheme A remains confined to the approved H1a-S2 phi result. H1b uses
%   formal HeXe_property_simulink values for three explicit cp-bar paths.

root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
config = defaultConfig(root);
if nargin > 0
    config = applyOptions(config, options);
end
validateConfig(config);

% H1a evidence identity is the first gate and has its own failure class.
h1aCsvHash = sha256File(config.h1aCsvPath);
h1aTxtHash = sha256File(config.h1aTxtPath);
if h1aCsvHash ~= lower(config.expectedH1aCsvSha256) || ...
        h1aTxtHash ~= lower(config.expectedH1aTxtSha256)
    error("steady53:H1bH1aEvidenceHashMismatch", ...
        "Approved H1a-S2 evidence hash mismatch.");
end

[hashes, archiveCommit] = validateProtectedIdentities(config, ...
    h1aCsvHash, h1aTxtHash);
h1aEvidence = validateH1aEvidence(config, hashes);

originalPath = path;
originalWarnings = warning;
loadedBefore = loadedBlockDiagrams();
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath, originalWarnings));
addpath(root, "-begin");
addpath(fullfile(root, "tests", "steady53"), "-begin");
clear("HeXe_property_simulink");

payload = load(config.inputMat, "result", "report", "spec");
inputs = validateAndExtractPayload(payload, hashes.modelSha256);
tablePayload = load(config.turbineTableMat, ...
    "bp_mf", "bp_speed", "table_eff");
inputs.eta = turbineEfficiency(tablePayload, ...
    inputs.lookupMassFlow_kg_s, inputs.lookupSpeed_rpm);
inputs.phiBar = h1aEvidence.phiBar;
inputs.T2s_K = h1aEvidence.T2s_K;

clear("HeXe_property_simulink");
[pointCp1, pointGamma1, pointRho1] = config.propertyFunction( ...
    inputs.T1_K, inputs.P1_Pa);
[pointCp2s, pointGamma2s, pointRho2s] = config.propertyFunction( ...
    h1aEvidence.pointCp2SourceT_K, inputs.P2_Pa);
validatePointProperty(pointCp1, pointGamma1, pointRho1);
validatePointProperty(pointCp2s, pointGamma2s, pointRho2s);
pointT2_K = inputs.T1_K-inputs.eta*(pointCp2s/pointCp1)* ...
    (inputs.T1_K-inputs.T2s_K);
pointResidual_K = pointT2_K-h1aEvidence.T2_K;
clear("HeXe_property_simulink");
if ~finiteRealScalar(pointT2_K) || abs(pointResidual_K) > 1e-9
    error("steady53:H1bBaselineMismatch", ...
        "The formal point-cp equation does not reproduce H1a-S2 within 1e-9 K.");
end

solverInputs = struct("T1_K", inputs.T1_K, ...
    "P1_Pa", inputs.P1_Pa, "P2_Pa", inputs.P2_Pa, ...
    "T2s_K", inputs.T2s_K, "eta", inputs.eta);
candidateCells = cell(1, numel(config.pathVariants));
for index = 1:numel(config.pathVariants)
    candidate = h1b_cpbar_candidate_readonly(solverInputs, ...
        config.pathVariants(index), config.propertyFunction, config.numerics);
    candidate.deltaT2FromH1a_K = candidate.T2_K-h1aEvidence.T2_K;
    candidate.remainingTargetError_K = inputs.targetT2_K-candidate.T2_K;
    candidate.explainedFractionOfH1aGap = ...
        candidate.deltaT2FromH1a_K/(inputs.targetT2_K-h1aEvidence.T2_K);
    candidate.targetDirectionMatched = ...
        sign(candidate.deltaT2FromH1a_K) == ...
        sign(inputs.targetT2_K-h1aEvidence.T2_K);
    candidate.h1bNumericallySufficient = ...
        candidate.targetDirectionMatched && ...
        abs(candidate.deltaT2FromH1a_K) >= ...
        abs(inputs.targetT2_K-h1aEvidence.T2_K);
    candidateCells{index} = candidate;
end
candidates = [candidateCells{:}];
clear("HeXe_property_simulink");

scope = struct( ...
    "h1aPhiPropertyVariant", "schemeA", ...
    "h1bCpbarPropertyVariant", "formalHeXeProperty", ...
    "T2sHeldFixed", true, ...
    "etaHeldFixed", true, ...
    "onlyPointCpReplacedByPathCpbar", true);
evidenceTable = makeEvidenceTable(config, hashes, archiveCommit, ...
    inputs, h1aEvidence, pointCp1, pointCp2s, candidates, scope);
summaryText = makeSummary(config, hashes, archiveCommit, inputs, ...
    h1aEvidence, pointCp1, pointGamma1, pointRho1, pointCp2s, ...
    pointGamma2s, pointRho2s, pointT2_K, pointResidual_K, ...
    candidates, scope);

loadedAfter = loadedBlockDiagrams();
if ~isequal(loadedAfter, loadedBefore)
    error("steady53:H1bEnvironmentChanged", ...
        "Loaded block diagrams changed during the read-only analyzer.");
end
postHashes = currentProtectedHashes(config);
if ~isequal(postHashes, hashes)
    error("steady53:H1bReadOnlyViolation", ...
        "A protected dependency changed during the read-only analyzer.");
end

[csvHash, summaryHash] = publishEvidence(config.outputDir, ...
    evidenceTable, summaryText, config.outputFailureHook);
csvPath = string(fullfile(config.outputDir, ...
    "h1b_cpbar_sensitivity.csv"));
summaryPath = string(fullfile(config.outputDir, ...
    "h1b_cpbar_summary.txt"));

clear("HeXe_property_simulink");
path(originalPath);
warning(originalWarnings);
clear environmentCleanup

analysis = struct( ...
    "runId", config.runId, ...
    "inputs", inputs, ...
    "scope", scope, ...
    "hashes", hashes, ...
    "archiveRef", config.archiveRef, ...
    "archiveCommit", archiveCommit, ...
    "h1aCandidateT2_K", h1aEvidence.T2_K, ...
    "h1aPointCpRecomputedT2_K", pointT2_K, ...
    "h1aPointCpReproductionResidual_K", pointResidual_K, ...
    "pointCp1_J_kgK", pointCp1, ...
    "pointCp2s_J_kgK", pointCp2s, ...
    "candidates", candidates, ...
    "evidenceTable", evidenceTable, ...
    "csvPath", csvPath, ...
    "summaryPath", summaryPath, ...
    "csvSha256", csvHash, ...
    "summarySha256", summaryHash, ...
    "loadedBlockDiagramsBefore", loadedBefore, ...
    "loadedBlockDiagramsAfter", loadedAfter, ...
    "propertyStateCanonicalCleared", true, ...
    "pathRestored", true, ...
    "warningsRestored", true, ...
    "h1aCandidateBaselineSelectedForExperiment", true, ...
    "h1aCandidateBaselinePromotedToFormalModel", false, ...
    "h1bExecuted", true, ...
    "h1bPressurePathSelectedAsFormal", false, ...
    "modelModified", false, ...
    "formalPropertyModified", false, ...
    "slxLoadedOrSimulated", false, ...
    "authorizesRepair", false, ...
    "formalModelPromotion", false, ...
    "task8Passed", false, ...
    "steady14000AcceptancePassed", false);
end

function config = defaultConfig(root)
runId = "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3";
h1aDir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h1a_s2_scheme_a", runId);
h2aDir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h2a", runId);
config = struct( ...
    "runId", runId, ...
    "inputMat", string(fullfile(root, "tmp", "steady53", "task8", ...
        runId, "nominal_500_report.mat")), ...
    "expectedInputSha256", ...
        "4ea018c7be06c5e577f107970dc2bf549924bf7a9a2989a89bcf1be76e98472b", ...
    "modelPath", string(fullfile(root, "final_steady_24a.slx")), ...
    "expectedModelSha256", ...
        "5423af38d6bbfc7730529475a6c4d046ef1386ec56782ba465c87dfae82cbf5d", ...
    "formalPropertyPath", string(fullfile(root, ...
        "HeXe_property_simulink.m")), ...
    "expectedFormalPropertySha256", ...
        "2490785cba7ae3d1f9bb4d4e52621f7b925945aab0f4f93e1a71b504783f5cf2", ...
    "turbineTableMat", string(fullfile(root, "turbine_table2.mat")), ...
    "expectedTurbineTableSha256", ...
        "cda85dc4480a7723a0ef52bda0fb6f2795e14dfe1167ac74b38a8d64d5b58c33", ...
    "schemeAHelperPath", string(fullfile(root, "tests", "steady53", ...
        "hexe_property_scheme_a_offline.m")), ...
    "expectedSchemeAHelperSha256", ...
        "5820e957b90b1affce777c1774aee6cc685f40430310408fb00f303846f606d0", ...
    "h1aCsvPath", string(fullfile(h1aDir, "h1a_sensitivity.csv")), ...
    "expectedH1aCsvSha256", ...
        "7e1ed139d14cbb1977a9f19d870c822243205414321a00c0f597717f5616f622", ...
    "h1aTxtPath", string(fullfile(h1aDir, "h1a_summary.txt")), ...
    "expectedH1aTxtSha256", ...
        "26248e95f42acbb70701193fa75af429b60659b9975277837331b8cd2803efd2", ...
    "h2aCsvPath", string(fullfile(h2aDir, ...
        "h2a_counterfactual_diagnostics.csv")), ...
    "expectedH2aCsvSha256", ...
        "6a8398b7a32685cb3d198a1fe39b3b9365cfdefe65143d5613c68ffdd44366f4", ...
    "h2aTxtPath", string(fullfile(h2aDir, "h2a_summary.txt")), ...
    "expectedH2aTxtSha256", ...
        "afd75b1b31cd0abdbdb2926b95ab987f260caa81a55fe2e901fdde4dafd72465", ...
    "archiveRef", "archive/pre-restart-20260824^{}", ...
    "expectedArchiveCommit", ...
        "8f625c268c35a95c18a626305c1aa6a79ae2ace7", ...
    "propertyFunction", @HeXe_property_simulink, ...
    "pathVariants", ["linearEndpointPressure" "constantP1" "constantP2"], ...
    "numerics", fixedNumerics(), ...
    "outputDir", string(fullfile(root, "tmp", "steady53", ...
        "task8_root_cause", "h1b_cpbar_from_h1a_s2_scheme_a", runId)), ...
    "outputFailureHook", @noOutputFailure);
end

function numerics = fixedNumerics()
numerics = struct("integralFunction", @integral, ...
    "rootFunction", @fzero, "integralRelTol", 1e-8, ...
    "integralAbsTol_J_kgK", 1e-8, "rootTolX_K", 1e-12, ...
    "rootMaxIterations", 1000, ...
    "rootMaxFunctionEvaluations", 5000, ...
    "rootAbsResidualTolerance_K", 1e-9, "auditSampleCount", 1001);
end

function config = applyOptions(config, options)
if ~isstruct(options) || ~isscalar(options) || ...
        ~isfield(options, "testOnly") || ~isequal(options.testOnly, true)
    invalidOptions("Non-default options require testOnly=true.");
end
actual = sort(string(fieldnames(options)));
convenience = sort(["testOnly"; "outputDir"]);
controlled = sort(["testOnly"; "testControl"]);
if isequal(actual, convenience)
    outputDir = string(options.outputDir);
    if ~isscalar(outputDir) || ismissing(outputDir) || ...
            strlength(outputDir) == 0 || ~startsWith(outputDir, filesep)
        invalidOptions("The test outputDir must be an absolute path.");
    end
    config.outputDir = outputDir;
elseif isequal(actual, controlled)
    control = options.testControl;
    if ~isstruct(control) || ~isscalar(control) || ...
            ~isequal(sort(string(fieldnames(control))), ...
            sort(string(fieldnames(config))))
        invalidOptions("testControl must state the exact complete contract.");
    end
    config = control;
else
    invalidOptions("Unknown or partial H1b test-only options.");
end
end

function validateConfig(config)
pathFields = ["inputMat" "modelPath" "formalPropertyPath" ...
    "turbineTableMat" "schemeAHelperPath" "h1aCsvPath" ...
    "h1aTxtPath" "h2aCsvPath" "h2aTxtPath" "outputDir"];
for field = pathFields
    value = string(config.(field));
    if ~isscalar(value) || ismissing(value) || strlength(value) == 0 || ...
            ~startsWith(value, filesep)
        invalidOptions(field+" must be an absolute path.");
    end
    config.(field) = value;
end
hashFields = ["expectedInputSha256" "expectedModelSha256" ...
    "expectedFormalPropertySha256" "expectedTurbineTableSha256" ...
    "expectedSchemeAHelperSha256" "expectedH1aCsvSha256" ...
    "expectedH1aTxtSha256" "expectedH2aCsvSha256" ...
    "expectedH2aTxtSha256"];
for field = hashFields
    value = string(config.(field));
    if ~isscalar(value) || isempty(regexp(char(value), ...
            '^[0-9a-fA-F]{64}$', 'once'))
        invalidOptions(field+" must be a SHA-256 value.");
    end
end
if config.runId ~= ...
        "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3" || ...
        config.archiveRef ~= "archive/pre-restart-20260824^{}" || ...
        config.expectedArchiveCommit ~= ...
        "8f625c268c35a95c18a626305c1aa6a79ae2ace7" || ...
        ~isa(config.propertyFunction, "function_handle") || ...
        ~isa(config.outputFailureHook, "function_handle") || ...
        ~isequal(config.pathVariants, ...
        ["linearEndpointPressure" "constantP1" "constantP2"])
    invalidOptions("The fixed H1b identity or function contract is invalid.");
end
end

function invalidOptions(message)
error("steady53:H1bInvalidOptions", "%s", message);
end

function [hashes, archiveCommit] = validateProtectedIdentities( ...
        config, h1aCsvHash, h1aTxtHash)
hashes = currentProtectedHashes(config);
hashes.h1aCsvSha256 = h1aCsvHash;
hashes.h1aTxtSha256 = h1aTxtHash;
checks = [ ...
    hashes.inputMatSha256 == lower(config.expectedInputSha256)
    hashes.modelSha256 == lower(config.expectedModelSha256)
    hashes.formalPropertySha256 == ...
        lower(config.expectedFormalPropertySha256)
    hashes.turbineTableSha256 == lower(config.expectedTurbineTableSha256)
    hashes.schemeAHelperSha256 == lower(config.expectedSchemeAHelperSha256)
    hashes.h2aCsvSha256 == lower(config.expectedH2aCsvSha256)
    hashes.h2aTxtSha256 == lower(config.expectedH2aTxtSha256)];
if ~all(checks)
    error("steady53:H1bProtectedHashMismatch", ...
        "A protected H1b dependency hash does not match its fixed identity.");
end
archiveCommit = resolveArchiveCommit(config.archiveRef);
if archiveCommit ~= lower(config.expectedArchiveCommit)
    error("steady53:H1bProtectedHashMismatch", ...
        "The restart archive ref no longer resolves to its fixed commit.");
end
end

function hashes = currentProtectedHashes(config)
hashes = struct( ...
    "h1aCsvSha256", sha256File(config.h1aCsvPath), ...
    "h1aTxtSha256", sha256File(config.h1aTxtPath), ...
    "inputMatSha256", sha256File(config.inputMat), ...
    "modelSha256", sha256File(config.modelPath), ...
    "formalPropertySha256", sha256File(config.formalPropertyPath), ...
    "turbineTableSha256", sha256File(config.turbineTableMat), ...
    "schemeAHelperSha256", sha256File(config.schemeAHelperPath), ...
    "h2aCsvSha256", sha256File(config.h2aCsvPath), ...
    "h2aTxtSha256", sha256File(config.h2aTxtPath));
end

function commit = resolveArchiveCommit(reference)
root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
command = sprintf('git -C "%s" rev-parse ''%s''', root, reference);
[status, output] = system(command);
commit = strtrim(string(output));
if status ~= 0 || isempty(regexp(char(commit), '^[0-9a-f]{40}$', 'once'))
    error("steady53:H1bProtectedHashMismatch", ...
        "Could not resolve the fixed restart archive ref.");
end
end

function evidence = validateH1aEvidence(config, hashes)
try
    csv = readtable(config.h1aCsvPath, "TextType", "string", ...
        "VariableNamingRule", "preserve");
catch exception
    invalid = MException("steady53:H1bInvalidH1aEvidence", ...
        "Approved H1a CSV is not parseable.");
    invalid = addCause(invalid, exception);
    throw(invalid);
end
required = ["method" "phiBar" "T2s_K" "T2_K" "runId" ...
    "inputMat" "inputMatSha256" "formalModel" "modelSha256" ...
    "formalProperty" "formalPropertySha256" "s2PropertySource" ...
    "s2PropertySourceSha256" "s2ApprovedH2aCsv" ...
    "s2ApprovedH2aCsvSha256" "s2ApprovedH2aTxt" ...
    "s2ApprovedH2aTxtSha256" "s2PhiVariant" "s2PhiScope" ...
    "schemeADefinition" "etaCp1Cp2HeldFixed" ...
    "s2IntegrationCompleted" "s2RootConverged" ...
    "s2PathAuditAllPhysical" "s2PathAuditFormalGlobalProof" ...
    "slxLoadedOrSimulated" "h1bExecuted" "authorizesRepair" ...
    "formalModelPromotion"];
methods = ["baseline"; "S1"; "S2_schemeA_phiOnly"];
if height(csv) ~= 3 || ...
        ~all(ismember(required, string(csv.Properties.VariableNames))) || ...
        ~isequal(sort(csv.method), sort(methods)) || ...
        nnz(csv.method == "S2_schemeA_phiOnly") ~= 1
    invalidH1a("H1a CSV rows, methods, or required columns are invalid.");
end
if any(csv.runId ~= config.runId) || ...
        any(csv.inputMat ~= config.inputMat) || ...
        any(csv.inputMatSha256 ~= hashes.inputMatSha256) || ...
        any(csv.formalModel ~= config.modelPath) || ...
        any(csv.modelSha256 ~= hashes.modelSha256) || ...
        any(csv.formalProperty ~= config.formalPropertyPath) || ...
        any(csv.formalPropertySha256 ~= hashes.formalPropertySha256) || ...
        any(csv.s2PropertySource ~= config.schemeAHelperPath) || ...
        any(csv.s2PropertySourceSha256 ~= hashes.schemeAHelperSha256) || ...
        any(csv.s2ApprovedH2aCsv ~= config.h2aCsvPath) || ...
        any(csv.s2ApprovedH2aCsvSha256 ~= hashes.h2aCsvSha256) || ...
        any(csv.s2ApprovedH2aTxt ~= config.h2aTxtPath) || ...
        any(csv.s2ApprovedH2aTxtSha256 ~= hashes.h2aTxtSha256)
    invalidH1a("H1a CSV dependency identities are invalid.");
end
if any(csv.s2PhiVariant ~= "schemeA") || ...
        any(csv.s2PhiScope ~= "only H1a-S2 phi integrand") || ...
        any(csv.schemeADefinition ~= ...
        "ignoreHePureThirdVirialBeforeCurrentMixingRule") || ...
        ~all(csv.etaCp1Cp2HeldFixed) || ...
        ~all(csv.s2IntegrationCompleted) || ~all(csv.s2RootConverged) || ...
        ~all(csv.s2PathAuditAllPhysical) || ...
        any(csv.s2PathAuditFormalGlobalProof) || ...
        any(csv.slxLoadedOrSimulated) || any(csv.h1bExecuted) || ...
        any(csv.authorizesRepair) || any(csv.formalModelPromotion)
    invalidH1a("H1a CSV scope or status boundaries are invalid.");
end
row = csv(csv.method == "S2_schemeA_phiOnly", :);
baselineRow = csv(csv.method == "baseline", :);
if ~near(row.phiBar, 0.39979002315209694, 1e-15) || ...
        ~near(row.T2s_K, 1089.5635709913104, 1e-12) || ...
        ~near(row.T2_K, 1143.6624955393854, 1e-9) || ...
        ~near(baselineRow.T2s_K, 1089.6475181122112, 1e-9)
    invalidH1a("H1a-S2 fixed numerical baseline is invalid.");
end
evidence = struct("phiBar", 0.39979002315209694, ...
    "T2s_K", 1089.5635709913104, "T2_K", 1143.6624955393854, ...
    "pointCp2SourceT_K", 1089.6475181122112);
end

function invalidH1a(message)
error("steady53:H1bInvalidH1aEvidence", "%s", message);
end

function valid = near(actual, expected, tolerance)
valid = finiteRealScalar(actual) && abs(double(actual)-expected) <= tolerance;
end

function inputs = validateAndExtractPayload(payload, expectedModelHash)
if ~isstruct(payload) || ~all(isfield(payload, ...
        ["result" "report" "spec"])) || ...
        ~isstruct(payload.result) || ~isstruct(payload.report) || ...
        ~isstruct(payload.spec)
    invalidInput("Missing result, report, or spec payload.");
end
result = payload.result;
report = payload.report;
spec = payload.spec;
if ~all(isfield(result, ["t" "signals" "modelHashBefore" ...
        "modelHashAfter"])) || ~isstruct(result.signals)
    invalidInput("Missing required result fields.");
end
t = double(result.t(:));
if numel(t) < 2 || any(~isfinite(t)) || any(diff(t) <= 0) || ...
        ~isfield(spec, "finalWindow_s") || numel(spec.finalWindow_s) ~= 2
    invalidInput("Recorded time or final-window evidence is invalid.");
end
window = double(spec.finalWindow_s(:));
if any(~isfinite(window)) || window(1) >= window(2) || ...
        window(1) < t(1) || window(2) > t(end) || ...
        nnz(t >= window(1) & t <= window(2)) < 2
    invalidInput("The final window is outside recorded coverage.");
end
if lower(string(result.modelHashBefore)) ~= expectedModelHash || ...
        lower(string(result.modelHashAfter)) ~= expectedModelHash
    invalidInput("Recorded model hashes do not match the protected model.");
end
requiredSignals = ["turbine_inlet_T" "turbine_inlet_P" ...
    "turbine_outlet_P" "turbine_outlet_T" ...
    "turbine_lookup_mass_flow" "turbine_lookup_speed_eff"];
for signal = requiredSignals
    if ~isfield(result.signals, signal)
        invalidInput("A required turbine signal is missing.");
    end
    values = result.signals.(signal);
    if ~isnumeric(values) || ~isvector(values) || numel(values) ~= numel(t) || ...
            ~isreal(values) || any(~isfinite(values))
        invalidInput("A required turbine signal is invalid.");
    end
end
if ~isfield(report, "metrics") || ~istable(report.metrics) || ...
        ~all(ismember(["metricName" "target"], ...
        string(report.metrics.Properties.VariableNames)))
    invalidInput("Report metrics are invalid.");
end
targetRow = string(report.metrics.metricName) == "turbine_outlet_T";
if nnz(targetRow) ~= 1 || ...
        ~finiteRealScalar(report.metrics.target(targetRow))
    invalidInput("The turbine outlet target is invalid.");
end
last = @(name) double(result.signals.(name)(end));
inputs = struct( ...
    "T1_K", last("turbine_inlet_T"), ...
    "P1_Pa", last("turbine_inlet_P"), ...
    "P2_Pa", last("turbine_outlet_P"), ...
    "recordedTerminalT2_K", last("turbine_outlet_T"), ...
    "lookupMassFlow_kg_s", last("turbine_lookup_mass_flow"), ...
    "lookupSpeed_rpm", last("turbine_lookup_speed_eff"), ...
    "targetT2_K", double(report.metrics.target(targetRow)), ...
    "tFinal_s", t(end), ...
    "finalWindow_s", window.');
scalarValues = [inputs.T1_K inputs.P1_Pa inputs.P2_Pa ...
    inputs.recordedTerminalT2_K inputs.lookupMassFlow_kg_s ...
    inputs.lookupSpeed_rpm inputs.targetT2_K];
if any(~isfinite(scalarValues)) || any(scalarValues <= 0)
    invalidInput("A terminal turbine value is outside its physical domain.");
end
end

function invalidInput(message)
error("steady53:H1bInvalidInput", "%s", message);
end

function eta = turbineEfficiency(tablePayload, massFlow, speed)
required = ["bp_mf" "bp_speed" "table_eff"];
if ~isstruct(tablePayload) || ~all(isfield(tablePayload, required))
    invalidInput("Turbine efficiency table fields are missing.");
end
bp_mf = double(tablePayload.bp_mf(:));
bp_speed = double(tablePayload.bp_speed(:));
table_eff = double(tablePayload.table_eff);
if numel(bp_mf) < 2 || numel(bp_speed) < 2 || ...
        any(~isfinite(bp_mf)) || any(~isfinite(bp_speed)) || ...
        any(diff(bp_mf) <= 0) || any(diff(bp_speed) <= 0) || ...
        ~isequal(size(table_eff), [numel(bp_mf) numel(bp_speed)]) || ...
        any(~isfinite(table_eff), "all") || ...
        massFlow < bp_mf(1) || massFlow > bp_mf(end) || ...
        speed < bp_speed(1) || speed > bp_speed(end)
    invalidInput("The turbine efficiency lookup contract is invalid.");
end
eta = interpn(bp_mf, bp_speed, table_eff, massFlow, speed, "linear");
if ~finiteRealScalar(eta) || eta <= 0 || eta >= 1
    invalidInput("The interpolated turbine efficiency is invalid.");
end
end

function validatePointProperty(cp, gamma, rho)
if ~finiteRealScalar(cp) || ~finiteRealScalar(gamma) || ...
        ~finiteRealScalar(rho) || cp <= 0 || gamma <= 1 || ...
        cp/gamma <= 0 || rho <= 0
    error("steady53:H1bBaselineMismatch", ...
        "The formal point property is nonphysical.");
end
end

function output = makeEvidenceTable(config, hashes, archiveCommit, ...
        inputs, h1a, pointCp1, pointCp2s, candidates, scope)
rows = repmat(commonRow(config, hashes, archiveCommit, inputs, h1a, ...
    pointCp1, pointCp2s, scope), 4, 1);
rows(1) = populateBaselineRow(rows(1), h1a);
for index = 1:3
    rows(index+1) = populateCandidateRow(rows(index+1), candidates(index));
end
output = struct2table(rows);
end

function row = commonRow(config, hashes, archiveCommit, inputs, h1a, ...
        pointCp1, pointCp2s, scope)
row = struct( ...
    "method", "", "pathVariant", "", "runId", config.runId, ...
    "inputMat", config.inputMat, "inputMatSha256", hashes.inputMatSha256, ...
    "formalModel", config.modelPath, "modelSha256", hashes.modelSha256, ...
    "formalProperty", config.formalPropertyPath, ...
    "formalPropertySha256", hashes.formalPropertySha256, ...
    "turbineTable", config.turbineTableMat, ...
    "turbineTableSha256", hashes.turbineTableSha256, ...
    "schemeAHelper", config.schemeAHelperPath, ...
    "schemeAHelperSha256", hashes.schemeAHelperSha256, ...
    "h1aCsv", config.h1aCsvPath, "h1aCsvSha256", hashes.h1aCsvSha256, ...
    "h1aTxt", config.h1aTxtPath, "h1aTxtSha256", hashes.h1aTxtSha256, ...
    "h2aCsv", config.h2aCsvPath, "h2aCsvSha256", hashes.h2aCsvSha256, ...
    "h2aTxt", config.h2aTxtPath, "h2aTxtSha256", hashes.h2aTxtSha256, ...
    "archiveRef", config.archiveRef, "archiveCommit", archiveCommit, ...
    "h1aPhiPropertyVariant", scope.h1aPhiPropertyVariant, ...
    "h1bCpbarPropertyVariant", scope.h1bCpbarPropertyVariant, ...
    "T2sHeldFixed", true, "etaHeldFixed", true, ...
    "onlyPointCpReplacedByPathCpbar", true, ...
    "T1_K", inputs.T1_K, "P1_Pa", inputs.P1_Pa, ...
    "P2_Pa", inputs.P2_Pa, "T2s_K", inputs.T2s_K, ...
    "eta", inputs.eta, "phiBar", inputs.phiBar, ...
    "h1aCandidateT2_K", h1a.T2_K, "targetT2_K", inputs.targetT2_K, ...
    "pointCp1_J_kgK", pointCp1, "pointCp2s_J_kgK", pointCp2s, ...
    "pointCp2SourceT_K", h1a.pointCp2SourceT_K, ...
    "pathIntegralApplicable", false, ...
    "cpBarIsentropic_J_kgK", NaN, "cpBarActual_J_kgK", NaN, ...
    "cpBarRatio", NaN, "T2_K", NaN, "deltaT2FromH1a_K", NaN, ...
    "remainingTargetError_K", NaN, ...
    "explainedFractionOfH1aGap", NaN, ...
    "targetDirectionMatched", false, ...
    "h1bNumericallySufficient", false, ...
    "integrationCompleted", false, "rootConverged", false, ...
    "rootResidual_K", NaN, "rootBracketLow_K", NaN, ...
    "rootBracketHigh_K", NaN, ...
    "idealPathAuditSampleCount", NaN, ...
    "idealPathAuditMinCpMass_J_kgK", NaN, ...
    "idealPathAuditMaxCpMass_J_kgK", NaN, ...
    "idealPathAuditMinCvMass_J_kgK", NaN, ...
    "idealPathAuditMaxCvMass_J_kgK", NaN, ...
    "idealPathAuditMinGamma", NaN, "idealPathAuditMaxGamma", NaN, ...
    "idealPathAuditMinRho_kg_m3", NaN, ...
    "idealPathAuditMaxRho_kg_m3", NaN, ...
    "idealPathAuditAllPhysical", false, ...
    "idealPathAuditFormalGlobalProof", false, ...
    "idealPathAuditClassification", "notApplicable", ...
    "actualPathAuditSampleCount", NaN, ...
    "actualPathAuditMinCpMass_J_kgK", NaN, ...
    "actualPathAuditMaxCpMass_J_kgK", NaN, ...
    "actualPathAuditMinCvMass_J_kgK", NaN, ...
    "actualPathAuditMaxCvMass_J_kgK", NaN, ...
    "actualPathAuditMinGamma", NaN, "actualPathAuditMaxGamma", NaN, ...
    "actualPathAuditMinRho_kg_m3", NaN, ...
    "actualPathAuditMaxRho_kg_m3", NaN, ...
    "actualPathAuditAllPhysical", false, ...
    "actualPathAuditFormalGlobalProof", false, ...
    "actualPathAuditClassification", "notApplicable", ...
    "integralRelTol", config.numerics.integralRelTol, ...
    "integralAbsTol_J_kgK", config.numerics.integralAbsTol_J_kgK, ...
    "rootTolX_K", config.numerics.rootTolX_K, ...
    "rootMaxIterations", config.numerics.rootMaxIterations, ...
    "rootMaxFunctionEvaluations", ...
        config.numerics.rootMaxFunctionEvaluations, ...
    "rootAbsResidualTolerance_K", ...
        config.numerics.rootAbsResidualTolerance_K, ...
    "h1aCandidateBaselineSelectedForExperiment", true, ...
    "h1aCandidateBaselinePromotedToFormalModel", false, ...
    "h1bExecuted", true, "h1bPressurePathSelectedAsFormal", false, ...
    "modelModified", false, "formalPropertyModified", false, ...
    "slxLoadedOrSimulated", false, "authorizesRepair", false, ...
    "formalModelPromotion", false, "task8Passed", false, ...
    "steady14000AcceptancePassed", false);
end

function row = populateBaselineRow(row, h1a)
row.method = "H1a_S2_schemeA_pointCp_baseline";
row.pathVariant = "notApplicable";
row.T2_K = h1a.T2_K;
row.deltaT2FromH1a_K = 0;
row.remainingTargetError_K = row.targetT2_K-h1a.T2_K;
row.explainedFractionOfH1aGap = 0;
end

function row = populateCandidateRow(row, candidate)
row.method = "H1b_"+candidate.pathVariant;
row.pathVariant = candidate.pathVariant;
row.pathIntegralApplicable = true;
row.cpBarIsentropic_J_kgK = candidate.cpBarIsentropic_J_kgK;
row.cpBarActual_J_kgK = candidate.cpBarActual_J_kgK;
row.cpBarRatio = candidate.cpBarRatio;
row.T2_K = candidate.T2_K;
row.deltaT2FromH1a_K = candidate.deltaT2FromH1a_K;
row.remainingTargetError_K = candidate.remainingTargetError_K;
row.explainedFractionOfH1aGap = candidate.explainedFractionOfH1aGap;
row.targetDirectionMatched = candidate.targetDirectionMatched;
row.h1bNumericallySufficient = candidate.h1bNumericallySufficient;
row.integrationCompleted = candidate.integrationCompleted;
row.rootConverged = candidate.rootConverged;
row.rootResidual_K = candidate.rootResidual_K;
row.rootBracketLow_K = candidate.rootBracket_K(1);
row.rootBracketHigh_K = candidate.rootBracket_K(2);
row = populateAudit(row, "ideal", candidate.idealPathAudit);
row = populateAudit(row, "actual", candidate.actualPathAudit);
end

function row = populateAudit(row, prefix, audit)
fieldPrefix = prefix+"PathAudit";
row.(fieldPrefix+"SampleCount") = audit.sampleCount;
row.(fieldPrefix+"MinCpMass_J_kgK") = audit.minCpMass_J_kgK;
row.(fieldPrefix+"MaxCpMass_J_kgK") = audit.maxCpMass_J_kgK;
row.(fieldPrefix+"MinCvMass_J_kgK") = audit.minCvMass_J_kgK;
row.(fieldPrefix+"MaxCvMass_J_kgK") = audit.maxCvMass_J_kgK;
row.(fieldPrefix+"MinGamma") = audit.minGamma;
row.(fieldPrefix+"MaxGamma") = audit.maxGamma;
row.(fieldPrefix+"MinRho_kg_m3") = audit.minRho_kg_m3;
row.(fieldPrefix+"MaxRho_kg_m3") = audit.maxRho_kg_m3;
row.(fieldPrefix+"AllPhysical") = audit.allPhysical;
row.(fieldPrefix+"FormalGlobalProof") = audit.formalGlobalProof;
row.(fieldPrefix+"Classification") = audit.classification;
end

function text = makeSummary(config, hashes, archiveCommit, inputs, h1a, ...
        cp1, gamma1, rho1, cp2s, gamma2s, rho2s, pointT2, ...
        pointResidual, candidates, scope)
lines = [ ...
    "Task 8 H1b read-only cp-bar sensitivity"
    "runId="+config.runId
    "inputMat="+config.inputMat
    "inputMatSha256="+hashes.inputMatSha256
    "formalModel="+config.modelPath
    "modelSha256="+hashes.modelSha256
    "formalProperty="+config.formalPropertyPath
    "formalPropertySha256="+hashes.formalPropertySha256
    "turbineTable="+config.turbineTableMat
    "turbineTableSha256="+hashes.turbineTableSha256
    "schemeAHelper="+config.schemeAHelperPath
    "schemeAHelperSha256="+hashes.schemeAHelperSha256
    "h1aCsv="+config.h1aCsvPath
    "h1aCsvSha256="+hashes.h1aCsvSha256
    "h1aTxt="+config.h1aTxtPath
    "h1aTxtSha256="+hashes.h1aTxtSha256
    "h2aCsv="+config.h2aCsvPath
    "h2aCsvSha256="+hashes.h2aCsvSha256
    "h2aTxt="+config.h2aTxtPath
    "h2aTxtSha256="+hashes.h2aTxtSha256
    "archiveRef="+config.archiveRef
    "archiveCommit="+archiveCommit
    "h1aPhiPropertyVariant="+scope.h1aPhiPropertyVariant
    "h1bCpbarPropertyVariant="+scope.h1bCpbarPropertyVariant
    "T2sHeldFixed=true"
    "etaHeldFixed=true"
    "onlyPointCpReplacedByPathCpbar=true"
    "equation=R(T2)=T2-[T1-eta*(cpBarIsentropic/cpBarActual)*(T1-T2s)]"
    "lambdaDomain=[0,1]"
    "T(lambda)=T1+lambda*(Tout-T1)"
    "linearEndpointPressure=P1+lambda*(P2-P1)"
    "constantP1=P1"
    "constantP2=P2"
    numericLine("T1_K", inputs.T1_K)
    numericLine("P1_Pa", inputs.P1_Pa)
    numericLine("P2_Pa", inputs.P2_Pa)
    numericLine("phiBar", inputs.phiBar)
    numericLine("T2s_K", inputs.T2s_K)
    numericLine("eta", inputs.eta)
    numericLine("targetT2_K", inputs.targetT2_K)
    numericLine("h1aCandidateT2_K", h1a.T2_K)
    numericLine("pointCp1_J_kgK", cp1)
    numericLine("pointGamma1", gamma1)
    numericLine("pointRho1_kg_m3", rho1)
    numericLine("pointCp2s_J_kgK", cp2s)
    numericLine("pointCp2SourceT_K", h1a.pointCp2SourceT_K)
    numericLine("pointGamma2s", gamma2s)
    numericLine("pointRho2s_kg_m3", rho2s)
    numericLine("h1aPointCpRecomputedT2_K", pointT2)
    numericLine("h1aPointCpReproductionResidual_K", pointResidual)
    numericLine("integralRelTol", config.numerics.integralRelTol)
    numericLine("integralAbsTol_J_kgK", ...
        config.numerics.integralAbsTol_J_kgK)
    numericLine("rootTolX_K", config.numerics.rootTolX_K)
    "rootMaxIterations="+string(config.numerics.rootMaxIterations)
    "rootMaxFunctionEvaluations="+ ...
        string(config.numerics.rootMaxFunctionEvaluations)
    numericLine("rootAbsResidualTolerance_K", ...
        config.numerics.rootAbsResidualTolerance_K)];
candidateBlocks = cell(numel(candidates), 1);
for index = 1:numel(candidates)
    candidate = candidates(index);
    prefix = "candidate."+candidate.pathVariant+".";
    candidateBlocks{index} = [ ...
        prefix+numericLine("cpBarIsentropic_J_kgK", ...
            candidate.cpBarIsentropic_J_kgK)
        prefix+numericLine("cpBarActual_J_kgK", ...
            candidate.cpBarActual_J_kgK)
        prefix+numericLine("cpBarRatio", candidate.cpBarRatio)
        prefix+numericLine("T2_K", candidate.T2_K)
        prefix+numericLine("rootResidual_K", candidate.rootResidual_K)
        prefix+numericLine("deltaT2FromH1a_K", ...
            candidate.deltaT2FromH1a_K)
        prefix+numericLine("remainingTargetError_K", ...
            candidate.remainingTargetError_K)
        prefix+numericLine("explainedFractionOfH1aGap", ...
            candidate.explainedFractionOfH1aGap)
        prefix+"targetDirectionMatched="+ ...
            logicalText(candidate.targetDirectionMatched)
        prefix+"h1bNumericallySufficient="+ ...
            logicalText(candidate.h1bNumericallySufficient)
        auditLines(prefix+"idealPathAudit.", candidate.idealPathAudit)
        auditLines(prefix+"actualPathAudit.", candidate.actualPathAudit)];
end
lines = [lines; vertcat(candidateBlocks{:})
    "h1aCandidateBaselineSelectedForExperiment=true"
    "h1aCandidateBaselinePromotedToFormalModel=false"
    "h1bExecuted=true"
    "h1bPressurePathSelectedAsFormal=false"
    "modelModified=false"
    "formalPropertyModified=false"
    "slxLoadedOrSimulated=false"
    "authorizesRepair=false"
    "formalModelPromotion=false"
    "task8Passed=false"
    "steady14000AcceptancePassed=false"
    "formalGlobalProof=false"
    "evidenceGrade.pathComputation=checked"
    "evidenceGrade.pathPhysicalSelection=unknown"
    "Boundary: numerical proximity to 1162 K is not correctness evidence."];
text = strjoin(lines, newline)+newline;
end

function line = numericLine(name, value)
line = string(sprintf("%s=%.17g", name, value));
end

function lines = auditLines(prefix, audit)
lines = [ ...
    prefix+"sampleCount="+string(audit.sampleCount)
    prefix+numericLine("minCpMass_J_kgK", audit.minCpMass_J_kgK)
    prefix+numericLine("maxCpMass_J_kgK", audit.maxCpMass_J_kgK)
    prefix+numericLine("minCvMass_J_kgK", audit.minCvMass_J_kgK)
    prefix+numericLine("maxCvMass_J_kgK", audit.maxCvMass_J_kgK)
    prefix+numericLine("minGamma", audit.minGamma)
    prefix+numericLine("maxGamma", audit.maxGamma)
    prefix+numericLine("minRho_kg_m3", audit.minRho_kg_m3)
    prefix+numericLine("maxRho_kg_m3", audit.maxRho_kg_m3)
    prefix+"allPhysical="+logicalText(audit.allPhysical)
    prefix+"formalGlobalProof="+logicalText(audit.formalGlobalProof)
    prefix+"classification="+audit.classification];
end

function text = logicalText(value)
if value
    text = "true";
else
    text = "false";
end
end

function [csvHash, summaryHash] = publishEvidence( ...
        outputDir, evidenceTable, summaryText, outputFailureHook)
[outputParent, outputName, outputExtension] = fileparts(outputDir);
outputParent = string(outputParent);
outputLeaf = string(outputName)+string(outputExtension);
if isfile(outputParent)
    error("steady53:H1bOutputFailed", ...
        "The H1b output parent exists as a non-directory.");
end
if ~isfolder(outputParent)
    [created, message] = mkdir(outputParent);
    if ~created || ~isfolder(outputParent)
        error("steady53:H1bOutputFailed", ...
            "Could not create H1b output parent: %s", message);
    end
end
if isfolder(outputDir) || isfile(outputDir)
    error("steady53:H1bOutputExists", ...
        "H1b output target already exists: '%s'.", outputDir);
end

stagingPrefix = "."+outputLeaf+".staging_";
[~, uniqueLeaf] = fileparts(tempname(outputParent));
stagingDir = string(fullfile(outputParent, ...
    stagingPrefix+string(uniqueLeaf)));
try
    [created, message] = mkdir(stagingDir);
    if ~created || ~isfolder(stagingDir)
        error("steady53:H1bOutputFailed", ...
            "Could not create H1b staging directory: %s", message);
    end
    stagingCleanup = onCleanup(@() cleanupStaging( ...
        stagingDir, outputParent, stagingPrefix));
    stagedCsv = fullfile(stagingDir, "h1b_cpbar_sensitivity.csv");
    stagedTxt = fullfile(stagingDir, "h1b_cpbar_summary.txt");
    writetable(evidenceTable, stagedCsv);
    outputFailureHook("afterCsvBeforeSummary", stagingDir);
    writeUtf8Text(stagedTxt, summaryText);
    validateStagedEvidence(stagedCsv, stagedTxt);
    csvHash = sha256File(stagedCsv);
    summaryHash = sha256File(stagedTxt);
    if isfolder(outputDir) || isfile(outputDir)
        error("steady53:H1bOutputExists", ...
            "H1b output target appeared before publication.");
    end
    outputFailureHook("beforePublish", stagingDir);
    moveDirectoryNoReplace(stagingDir, outputDir);
    if sha256File(fullfile(outputDir, "h1b_cpbar_sensitivity.csv")) ~= ...
            csvHash || ...
            sha256File(fullfile(outputDir, "h1b_cpbar_summary.txt")) ~= ...
            summaryHash
        cleanupPublished(outputDir, outputParent, outputLeaf);
        error("steady53:H1bOutputFailed", ...
            "Published H1b hashes differ from staged hashes.");
    end
    clear stagingCleanup
catch exception
    if exist("stagingDir", "var")
        cleanupStaging(stagingDir, outputParent, stagingPrefix);
    end
    if exception.identifier == "steady53:H1bOutputExists"
        rethrow(exception);
    end
    failure = MException("steady53:H1bOutputFailed", ...
        "Transactional H1b evidence publication failed.");
    failure = addCause(failure, exception);
    throw(failure);
end
end

function writeUtf8Text(filePath, text)
[fileId, message] = fopen(filePath, "w", "native", "UTF-8");
if fileId < 0
    error("steady53:H1bOutputFailed", ...
        "Could not create staged H1b summary: %s", message);
end
try
    fprintf(fileId, "%s", text);
catch exception
    fclose(fileId);
    rethrow(exception);
end
status = fclose(fileId);
if status ~= 0
    error("steady53:H1bOutputFailed", ...
        "Could not close staged H1b summary.");
end
end

function validateStagedEvidence(csvPath, txtPath)
csv = readtable(csvPath, "TextType", "string", ...
    "VariableNamingRule", "preserve");
summary = string(fileread(txtPath));
expectedMethods = sort([ ...
    "H1a_S2_schemeA_pointCp_baseline"
    "H1b_linearEndpointPressure"
    "H1b_constantP1"
    "H1b_constantP2"]);
if height(csv) ~= 4 || ~isequal(sort(csv.method), expectedMethods) || ...
        ~contains(summary, "h1bPressurePathSelectedAsFormal=false") || ...
        ~contains(summary, "slxLoadedOrSimulated=false")
    error("steady53:H1bOutputFailed", ...
        "Staged H1b evidence is incomplete or not self-consistent.");
end
end

function moveDirectoryNoReplace(stagingDir, outputDir)
sourcePath = javaObject("java.io.File", char(stagingDir)).toPath();
targetPath = javaObject("java.io.File", char(outputDir)).toPath();
noReplaceOptions = javaArray("java.nio.file.CopyOption", 0);
try
    javaMethod("move", "java.nio.file.Files", ...
        sourcePath, targetPath, noReplaceOptions);
catch exception
    if isfolder(outputDir) || isfile(outputDir)
        collision = MException("steady53:H1bOutputExists", ...
            "H1b publication refused to overwrite the target.");
        collision = addCause(collision, exception);
        throw(collision);
    end
    rethrow(exception);
end
end

function cleanupStaging(stagingDir, expectedParent, expectedPrefix)
if ~isfolder(stagingDir)
    return
end
[actualParent, actualName, actualExtension] = fileparts(stagingDir);
actualLeaf = string(actualName)+string(actualExtension);
if string(actualParent) == expectedParent && ...
        startsWith(actualLeaf, expectedPrefix) && ...
        strlength(actualLeaf) > strlength(expectedPrefix)
    rmdir(stagingDir, "s");
end
end

function cleanupPublished(outputDir, expectedParent, expectedLeaf)
if ~isfolder(outputDir)
    return
end
[actualParent, actualName, actualExtension] = fileparts(outputDir);
actualLeaf = string(actualName)+string(actualExtension);
if string(actualParent) == expectedParent && actualLeaf == expectedLeaf
    rmdir(outputDir, "s");
end
end

function restoreEnvironment(originalPath, originalWarnings)
clear("HeXe_property_simulink");
path(originalPath);
warning(originalWarnings);
end

function diagrams = loadedBlockDiagrams()
diagrams = sort(string(find_system("type", "block_diagram")));
diagrams = diagrams(:);
end

function noOutputFailure(~, ~)
end

function valid = finiteRealScalar(value)
valid = isnumeric(value) && isscalar(value) && isreal(value) && isfinite(value);
end

function hashValue = sha256File(filePath)
if ~isfile(filePath)
    error("steady53:H1bProtectedHashMismatch", ...
        "Required protected file does not exist: '%s'.", filePath);
end
digest = java.security.MessageDigest.getInstance("SHA-256");
fileBytes = java.nio.file.Files.readAllBytes( ...
    java.io.File(char(filePath)).toPath());
bytes = typecast(digest.digest(fileBytes), "uint8");
hashValue = lower(join(compose("%02x", bytes), ""));
end
