function analysis = analyze_task8_h2a_he_third_virial_counterfactual(options)
%ANALYZE_TASK8_H2A_HE_THIRD_VIRIAL_COUNTERFACTUAL Locks the H2a Task 1 contract.
%   This function verifies the approved read-only inputs and delegates only
%   to the approved H2 analyzer. Task 1 performs no counterfactual calculation
%   and creates no output artifact.

root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
config = defaultConfig(root);
if nargin > 0
    config = applyTestOnlyOptions(config, options);
end
validateConfig(config);

protectedBefore = protectedHashes(config);
validateProtectedHashes(protectedBefore, config);
archivePeeledCommit = validateArchiveIdentity( ...
    root, config.archiveTag, config.expectedArchivePeeledCommit);

originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(root, "-begin");
h2 = analyze_task8_h2_hexe_property_readonly();
clear pathCleanup
runIdMatches = h2.inputs.runId == config.runId;
exceptionPointMatches = ...
    h2.inputs.exceptionT_K == config.exceptionT_K && ...
    h2.inputs.exceptionP_Pa == config.exceptionP_Pa;
validateApprovedH2Identity(h2, config, archivePeeledCommit);

protectedAfter = protectedHashes(config);
protectedAssetsUnchanged = isequaln(protectedAfter, protectedBefore);
if ~protectedAssetsUnchanged
    error("steady53:H2aProtectedAssetChanged", ...
        "A protected H2a Task 1 input changed during the read-only audit.");
end
if ~runIdMatches || ~exceptionPointMatches
    error("steady53:H2aBaselineParityMismatch", ...
        "The approved H2 baseline identity does not match H2a Task 1.");
end

analysis = struct();
analysis.inputs = struct( ...
    "runId", config.runId, ...
    "exceptionT_K", config.exceptionT_K, ...
    "exceptionP_Pa", config.exceptionP_Pa);
analysis.sourceAudit = sourceAudit(config, protectedBefore, ...
    protectedAfter, archivePeeledCommit);
analysis.approval = struct( ...
    "scheme", "A", ...
    "variant", "ignoreHePureThirdVirialBeforeCurrentMixingRule", ...
    "pureHeliumThirdVirialTerm", "C111", ...
    "pureHeliumThirdVirialTreatment", "setToZero", ...
    "treatmentStage", "beforeCurrentMixingRule", ...
    "currentMixingRule", "unchanged", ...
    "allOtherPropertyTerms", "unchanged", ...
    "authorizesRepair", false, ...
    "loadsOrSimulatesSlx", false, ...
    "publishesArtifacts", false);
analysis.baselineParity = struct( ...
    "status", "verifiedReadOnlyAgainstApprovedH2", ...
    "evidenceGrade", "✅", ...
    "runIdMatches", runIdMatches, ...
    "exceptionPointMatches", exceptionPointMatches, ...
    "protectedAssetsUnchanged", protectedAssetsUnchanged);
placeholder = struct( ...
    "status", "notComputedInTask1", ...
    "evidenceGrade", "❓");
analysis.exceptionPoint = placeholder;
analysis.fixedPressureSweep = placeholder;
analysis.h1aPathSweep = placeholder;
analysis.counterfactualVerdict = placeholder;
end

function config = defaultConfig(root)
runId = "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3";
h2Dir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h2", runId);
config = struct();
config.testOnly = false;
config.runId = runId;
config.exceptionT_K = 992.38742737169468;
config.exceptionP_Pa = 1007910.8613125964;
config.modelPath = string(fullfile(root, "final_steady_24a.slx"));
config.expectedModelSha256 = ...
    "5423af38d6bbfc7730529475a6c4d046ef1386ec56782ba465c87dfae82cbf5d";
config.propertyPath = string(fullfile(root, "HeXe_property_simulink.m"));
config.expectedPropertySha256 = ...
    "2490785cba7ae3d1f9bb4d4e52621f7b925945aab0f4f93e1a71b504783f5cf2";
config.compressorMatPath = string(fullfile(root, ...
    "hexe_compressor_lookup.mat"));
config.expectedCompressorMatSha256 = ...
    "f9c85bc1ae831333fac5f868f15a6f82ea1c1716ee17f23dfb301f4618c9f579";
config.radiatorMatPath = string(fullfile(root, "radiator_table.mat"));
config.expectedRadiatorMatSha256 = ...
    "3f6e8a08f6ec9253b84d07f8eff11d2b093f785bafcfde515f2c6af4ec263304";
config.turbine1MatPath = string(fullfile(root, "turbine_table1.mat"));
config.expectedTurbine1MatSha256 = ...
    "10e72638374c530e2032d9bfe39b060d4181b0467bf69e03196efa0b90c4971d";
config.turbine2MatPath = string(fullfile(root, "turbine_table2.mat"));
config.expectedTurbine2MatSha256 = ...
    "cda85dc4480a7723a0ef52bda0fb6f2795e14dfe1167ac74b38a8d64d5b58c33";
config.inputMatPath = string(fullfile(root, "tmp", "steady53", "task8", ...
    runId, "nominal_500_report.mat"));
config.expectedInputMatSha256 = ...
    "4ea018c7be06c5e577f107970dc2bf549924bf7a9a2989a89bcf1be76e98472b";
config.thesisPdfPath = string(fullfile( ...
    "/Users/ikunsredemptionmac/Downloads/不接入转子稳态模型", ...
    "空间锂冷堆He-Xe布雷顿循环发电系统优化设计与运行特性分析_徐驰.pdf"));
config.expectedThesisPdfSha256 = ...
    "983bfc23712221f30202a47875cbe34c9559edf79b9c332aa20931b6075e4e7a";
config.approvedH2CsvPath = string(fullfile( ...
    h2Dir, "h2_property_diagnostics.csv"));
config.expectedApprovedH2CsvSha256 = ...
    "b2998bdafd96cdd49d9fa4ff621dc586add229dd525a9d0d79a7c22fc71ee9d6";
config.approvedH2TxtPath = string(fullfile(h2Dir, "h2_summary.txt"));
config.expectedApprovedH2TxtSha256 = ...
    "1fa29cebd816d891fecddfa8c54863d1f672f44a8793cb6e32cf3084241f9799";
config.archiveTag = "archive/pre-restart-20260824";
config.expectedArchivePeeledCommit = ...
    "8f625c268c35a95c18a626305c1aa6a79ae2ace7";
end

function config = applyTestOnlyOptions(config, options)
allowed = [ ...
    "testOnly" "runId" "exceptionT_K" "exceptionP_Pa" ...
    "modelPath" "expectedModelSha256" ...
    "propertyPath" "expectedPropertySha256" ...
    "compressorMatPath" "expectedCompressorMatSha256" ...
    "radiatorMatPath" "expectedRadiatorMatSha256" ...
    "turbine1MatPath" "expectedTurbine1MatSha256" ...
    "turbine2MatPath" "expectedTurbine2MatSha256" ...
    "inputMatPath" "expectedInputMatSha256" ...
    "thesisPdfPath" "expectedThesisPdfSha256" ...
    "approvedH2CsvPath" "expectedApprovedH2CsvSha256" ...
    "approvedH2TxtPath" "expectedApprovedH2TxtSha256" ...
    "archiveTag" "expectedArchivePeeledCommit"];
if ~isstruct(options) || ~isscalar(options) || ...
        ~isfield(options, "testOnly") || ~isequal(options.testOnly, true) || ...
        numel(fieldnames(options)) ~= numel(allowed) || ...
        ~all(ismember(allowed, string(fieldnames(options))))
    error("steady53:H2aInvalidOptions", ...
        "Test-only options must provide the complete approved contract.");
end
for index = 1:numel(allowed)
    config.(allowed(index)) = options.(allowed(index));
end
end

function validateConfig(config)
approvedRunId = ...
    "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3";
if ~isscalar(string(config.runId)) || config.runId ~= approvedRunId
    error("steady53:H2aRunIdMismatch", ...
        "H2a Task 1 run ID does not match the approved H2 run.");
end
if ~isscalar(config.exceptionT_K) || ~isreal(config.exceptionT_K) || ...
        ~isfinite(config.exceptionT_K) || ...
        ~isscalar(config.exceptionP_Pa) || ~isreal(config.exceptionP_Pa) || ...
        ~isfinite(config.exceptionP_Pa) || ...
        config.exceptionT_K ~= 992.38742737169468 || ...
        config.exceptionP_Pa ~= 1007910.8613125964
    error("steady53:H2aExceptionPointMismatch", ...
        "H2a Task 1 exception point is not the approved H2 point.");
end

pathFields = ["modelPath" "propertyPath" "compressorMatPath" ...
    "radiatorMatPath" "turbine1MatPath" "turbine2MatPath" ...
    "inputMatPath" "thesisPdfPath" "approvedH2CsvPath" ...
    "approvedH2TxtPath"];
for field = pathFields
    value = string(config.(field));
    if ~isscalar(value) || ismissing(value) || strlength(value) == 0 || ...
            ~startsWith(value, filesep)
        error("steady53:H2aInvalidOptions", ...
            "Every H2a Task 1 source path must be absolute.");
    end
end

hashFields = ["expectedModelSha256" "expectedPropertySha256" ...
    "expectedCompressorMatSha256" "expectedRadiatorMatSha256" ...
    "expectedTurbine1MatSha256" "expectedTurbine2MatSha256" ...
    "expectedInputMatSha256" "expectedThesisPdfSha256" ...
    "expectedApprovedH2CsvSha256" "expectedApprovedH2TxtSha256"];
for field = hashFields
    value = char(string(config.(field)));
    if isempty(regexp(value, '^[0-9a-fA-F]{64}$', 'once'))
        error("steady53:H2aInvalidOptions", ...
            "Every expected H2a Task 1 file hash must be SHA-256.");
    end
end
if isempty(regexp(char(string(config.expectedArchivePeeledCommit)), ...
        '^[0-9a-fA-F]{40}$', 'once'))
    error("steady53:H2aInvalidOptions", ...
        "The expected H2a archive commit must be a Git SHA-1 ID.");
end
end

function hashes = protectedHashes(config)
name = ["model"; "property"; "compressorMat"; "radiatorMat"; ...
    "turbine1Mat"; "turbine2Mat"; "inputMat"; "thesisPdf"; ...
    "approvedH2Csv"; "approvedH2Txt"];
pathValue = [config.modelPath; config.propertyPath; ...
    config.compressorMatPath; config.radiatorMatPath; ...
    config.turbine1MatPath; config.turbine2MatPath; ...
    config.inputMatPath; config.thesisPdfPath; ...
    config.approvedH2CsvPath; config.approvedH2TxtPath];
sha256 = strings(numel(pathValue), 1);
for index = 1:numel(pathValue)
    sha256(index) = sha256File(pathValue(index));
end
hashes = table(name, pathValue, sha256);
end

function validateProtectedHashes(hashes, config)
expected = [config.expectedModelSha256; config.expectedPropertySha256; ...
    config.expectedCompressorMatSha256; ...
    config.expectedRadiatorMatSha256; ...
    config.expectedTurbine1MatSha256; ...
    config.expectedTurbine2MatSha256; config.expectedInputMatSha256; ...
    config.expectedThesisPdfSha256; ...
    config.expectedApprovedH2CsvSha256; ...
    config.expectedApprovedH2TxtSha256];
identifiers = [ ...
    "steady53:H2aModelHashMismatch"
    "steady53:H2aPropertyHashMismatch"
    "steady53:H2aCompressorMatHashMismatch"
    "steady53:H2aRadiatorMatHashMismatch"
    "steady53:H2aTurbine1MatHashMismatch"
    "steady53:H2aTurbine2MatHashMismatch"
    "steady53:H2aInputMatHashMismatch"
    "steady53:H2aThesisPdfHashMismatch"
    "steady53:H2aApprovedH2CsvHashMismatch"
    "steady53:H2aApprovedH2TxtHashMismatch"];
for index = 1:height(hashes)
    if hashes.sha256(index) ~= lower(string(expected(index)))
        error(identifiers(index), ...
            "H2a Task 1 protected hash mismatch for '%s'.", ...
            hashes.pathValue(index));
    end
end
end

function commit = validateArchiveIdentity(root, tagName, expectedCommit)
approvedTag = "archive/pre-restart-20260824";
if ~isscalar(string(tagName)) || string(tagName) ~= approvedTag
    error("steady53:H2aArchiveTagMismatch", ...
        "H2a Task 1 archive tag is not the approved tag.");
end
command = "git -C " + shellQuote(root) + " rev-list -n 1 " + ...
    shellQuote(tagName);
[status, output] = system(command);
commit = lower(strtrim(string(output)));
if status ~= 0 || ...
        commit ~= lower(string(expectedCommit)) || ...
        commit ~= "8f625c268c35a95c18a626305c1aa6a79ae2ace7"
    error("steady53:H2aArchiveCommitMismatch", ...
        "H2a Task 1 archive tag does not resolve to the approved commit.");
end
end

function validateApprovedH2Identity(h2, config, archiveCommit)
matches = h2.sourceAudit.modelSha256 == config.expectedModelSha256 && ...
    h2.sourceAudit.propertySha256 == config.expectedPropertySha256 && ...
    h2.sourceAudit.inputMatSha256 == config.expectedInputMatSha256 && ...
    h2.sourceAudit.paperPdfSha256 == config.expectedThesisPdfSha256 && ...
    h2.sourceAudit.archiveTag == config.archiveTag && ...
    h2.sourceAudit.archivePeeledCommit == archiveCommit;
if ~matches
    error("steady53:H2aBaselineParityMismatch", ...
        "The read-only H2 baseline does not match the approved H2a sources.");
end
end

function audit = sourceAudit(config, before, after, archiveCommit)
audit = struct( ...
    "modelSha256", config.expectedModelSha256, ...
    "propertySha256", config.expectedPropertySha256, ...
    "compressorMatSha256", config.expectedCompressorMatSha256, ...
    "radiatorMatSha256", config.expectedRadiatorMatSha256, ...
    "turbine1MatSha256", config.expectedTurbine1MatSha256, ...
    "turbine2MatSha256", config.expectedTurbine2MatSha256, ...
    "inputMatSha256", config.expectedInputMatSha256, ...
    "thesisPdfSha256", config.expectedThesisPdfSha256, ...
    "approvedH2CsvSha256", config.expectedApprovedH2CsvSha256, ...
    "approvedH2TxtSha256", config.expectedApprovedH2TxtSha256, ...
    "archiveTag", config.archiveTag, ...
    "archivePeeledCommit", archiveCommit, ...
    "approvedH2Outputs", struct( ...
        "csv", struct("path", config.approvedH2CsvPath, ...
            "sha256", config.expectedApprovedH2CsvSha256), ...
        "txt", struct("path", config.approvedH2TxtPath, ...
            "sha256", config.expectedApprovedH2TxtSha256)), ...
    "protectedAssetHashesBefore", before, ...
    "protectedAssetHashesAfter", after);
end

function hash = sha256File(filePath)
[status, output] = system("shasum -a 256 " + shellQuote(filePath));
if status ~= 0
    error("steady53:H2aHashFailure", ...
        "Could not hash H2a Task 1 source '%s'.", filePath);
end
parts = split(strtrim(string(output)));
hash = lower(parts(1));
end

function quoted = shellQuote(value)
quoted = "'" + replace(string(value), "'", "'\''") + "'";
end
