function [manifest, stateMeta] = steady53_signal_manifest(model)
%STEADY53_SIGNAL_MANIFEST Explicit signal and state audit metadata.
%   The entries below were traced against final_steady_24a.slx. State
%   semantics are deliberately explicit: formal audits must not infer fluid,
%   kind, or sign policy from a block path at run time.

arguments
    model (1, 1) string
end

signal = @(name, block, port, fluid) struct( ...
    "name", string(name), ...
    "block", model + "/" + string(block), ...
    "port", double(port), ...
    "fluid", string(fluid));

manifest = [ ...
    signal("reactor_inlet_T", "IHX", 1, "Lithium"); ...
    signal("turbine_inlet_P", "IHX", 2, "none"); ...
    signal("turbine_inlet_T", "IHX", 3, "HeXe"); ...
    signal("reactor_outlet_T", "reactor", 1, "Lithium"); ...
    signal("turbine_outlet_P", "TAC", 1, "none"); ...
    signal("turbine_outlet_T", "TAC", 3, "HeXe"); ...
    signal("compressor_outlet_T", "TAC", 4, "HeXe"); ...
    signal("compressor_outlet_P", "TAC", 6, "none"); ...
    signal("recuperator_hot_outlet_T", "recuperator", 1, "HeXe"); ...
    signal("recuperator_hot_outlet_P", "recuperator", 2, "none"); ...
    signal("recuperator_cold_outlet_P", "recuperator", 4, "none"); ...
    signal("recuperator_cold_outlet_T", "recuperator", 6, "HeXe"); ...
    signal("compressor_inlet_P", "precooler", 2, "none"); ...
    signal("compressor_inlet_T", "precooler", 3, "HeXe"); ...
    signal("cooler_cold_outlet_T", "precooler", 4, "none"); ...
    signal("cooler_cold_inlet_T", "rediator", 1, "none"); ...
    signal("turbine_power", "TAC/Turbine", 4, "none"); ...
    signal("compressor_power", "TAC/Compressor", 2, "none"); ...
    signal("rotor_speed", "TAC/Constant", 1, "none"); ...
    ... % Compressor pressure ratio r is passed directly to Turbine input r.
    signal("turbine_expansion_ratio", "TAC/Compressor", 1, "none"); ...
    signal("hexe_mdot_turbine", "TAC", 2, "HeXe"); ...
    signal("hexe_mdot_compressor", "TAC", 5, "HeXe"); ...
    signal("hexe_mdot_ihx", "IHX", 5, "HeXe"); ...
    signal("hexe_mdot_recup_hot", "recuperator", 3, "HeXe"); ...
    signal("hexe_mdot_recup_cold", "recuperator", 5, "HeXe"); ...
    signal("lithium_mdot_reactor", "reactor", 2, "Lithium"); ...
    signal("lithium_mdot_ihx", "IHX", 4, "Lithium"); ...
    ... % Inputs to the two compressor map tables.
    signal("compressor_lookup_speed_eff", "TAC/Compressor/Gain2", 1, "none"); ...
    signal("compressor_lookup_flow_eff", "TAC/Compressor/Gain4", 1, "none"); ...
    signal("compressor_lookup_speed_pr", "TAC/Compressor/Gain1", 1, "none"); ...
    signal("compressor_lookup_flow_pr", "TAC/Compressor/Gain3", 1, "none"); ...
    ... % Inputs to the two turbine map tables.
    signal("turbine_lookup_expansion_ratio", "TAC/Turbine/Product2", 1, "none"); ...
    signal("turbine_lookup_speed_flow", "TAC/Turbine/From2", 1, "none"); ...
    signal("turbine_lookup_mass_flow", "TAC/Turbine/From24", 1, "none"); ...
    signal("turbine_lookup_speed_eff", "TAC/Turbine/From3", 1, "none")];

state = @(path, fluid, kind, signPolicy) struct( ...
    "path", model + "/" + string(path), ...
    "fluid", string(fluid), ...
    "kind", string(kind), ...
    "signPolicy", string(signPolicy));

stateMeta = [ ...
    state("IHX/IHX_region_1/T_c1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("IHX/IHX_region_1/T_c2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("IHX/IHX_region_1/T_h1_average_Integrator", "Lithium", "temperature", "positive"); ...
    state("IHX/IHX_region_1/T_h2_out_Integrator", "Lithium", "temperature", "positive"); ...
    state("IHX/IHX_region_1/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("IHX/IHX_region_2/T_c1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("IHX/IHX_region_2/T_c2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("IHX/IHX_region_2/T_h1_average_Integrator", "Lithium", "temperature", "positive"); ...
    state("IHX/IHX_region_2/T_h2_out_Integrator", "Lithium", "temperature", "positive"); ...
    state("IHX/IHX_region_2/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("TAC/rotor/N_rpm_Integrator", "none", "speed", "nonnegative"); ...
    state("precooler/precooler_1/T_c1_average_Integrator", "none", "temperature", "positive"); ...
    state("precooler/precooler_1/T_c2_out_Integrator", "none", "temperature", "positive"); ...
    state("precooler/precooler_1/T_h1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("precooler/precooler_1/T_h2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("precooler/precooler_1/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("precooler/precooler_2/T_c1_average_Integrator", "none", "temperature", "positive"); ...
    state("precooler/precooler_2/T_c2_out_Integrator", "none", "temperature", "positive"); ...
    state("precooler/precooler_2/T_h1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("precooler/precooler_2/T_h2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("precooler/precooler_2/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("reactor/Integrator", "none", "other", "nonnegative"); ...
    state("reactor/Integrator1", "none", "other", "nonnegative"); ...
    state("reactor/Integrator2", "none", "other", "nonnegative"); ...
    state("reactor/Integrator3", "none", "other", "nonnegative"); ...
    state("reactor/Integrator4", "none", "other", "nonnegative"); ...
    state("reactor/Integrator5", "none", "other", "nonnegative"); ...
    state("reactor/Integrator6", "none", "power", "nonnegative"); ...
    state("reactor/Integrator7", "none", "temperature", "positive"); ...
    state("recuperator/MannRegion_1/T_c1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_1/T_c2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_1/T_h1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_1/T_h2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_1/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("recuperator/MannRegion_2/T_c1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_2/T_c2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_2/T_h1_average_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_2/T_h2_out_Integrator", "HeXe", "temperature", "positive"); ...
    state("recuperator/MannRegion_2/T_wall_Integrator", "none", "temperature", "positive"); ...
    state("rediator/T_rad_Integrator", "none", "temperature", "positive")];
end
