function boundaries = steady53_component_boundaries()
%STEADY53_COMPONENT_BOUNDARIES Fixed Section 5.3.1 harness inputs.
%   Sources and evidence grades are per input. Approved project boundaries
%   are labelled as such and are not promoted to thesis-direct values.

boundaries = struct();
boundaries.IHX = item( ...
    [1600 4.572 11.97 1100.91 1.543e6], ...
    ["T_hi" "mdot_Li" "mdot_HeXe" "T_ci" "P_ci"], ...
    ["T_ho" "P_co" "T_co" "mdot_Li_out" "mdot_c_out"], ...
    ["Thesis Table 5.2 direct temperature" ...
     "Approved project lithium mass-flow boundary; not thesis direct" ...
     "Approved project He-Xe mass-flow boundary" ...
     "Thesis Table 5.2 direct temperature" ...
     "Thesis Table 5.2 direct pressure"], ...
    ["✅ thesis direct" "❓ project boundary" "❓ project boundary" ...
     "✅ thesis direct" "✅ thesis direct"]);

boundaries.recuperator = item( ...
    [11.97 1162 0.676e6 1.551e6 601.90 11.97], ...
    ["mdot_h_in" "T_h_in" "P_h" "P_c" "T_c_in" "mdot_c_in"], ...
    ["T_h,o" "P_h,o" "mdot_h_out" "P_c,o" "mdot_c_out" "T_c,o"], ...
    ["Approved project He-Xe mass-flow boundary" ...
     "Thesis Table 5.2 direct temperature" ...
     "Thesis Table 5.2 direct pressure" ...
     "Thesis Table 5.2 direct pressure" ...
     "Thesis Table 5.2 direct temperature" ...
     "Approved project He-Xe mass-flow boundary"], ...
    ["❓ project boundary" "✅ thesis direct" "✅ thesis direct" ...
     "✅ thesis direct" "✅ thesis direct" "❓ project boundary"]);

boundaries.precooler = item( ...
    [360.10 6.95 663.63 0.676e6 11.97], ...
    ["T_c_in" "mdot_c_in" "T_h_in" "P_h" "mdot_h_in"], ...
    ["mdot_h_out" "P_h,o" "T_h,o" "T_c,o" "mdot_c_out"], ...
    ["Thesis Table 5.2 direct temperature" ...
     "Approved project coolant mass-flow boundary; not thesis direct" ...
     "Thesis Table 5.2 direct temperature" ...
     "Thesis Table 5.2 direct pressure" ...
     "Approved project He-Xe mass-flow boundary"], ...
    ["✅ thesis direct" "❓ project boundary" "✅ thesis direct" ...
     "✅ thesis direct" "❓ project boundary"]);

boundaries.rediator = item( ...
    [609.58 6.95], ["T_hi" "m_hi"], ...
    ["T_ho" "m_ho"], ...
    ["Thesis Table 5.2 direct temperature" ...
     "Approved project coolant mass-flow boundary; not thesis direct"], ...
    ["✅ thesis direct" "❓ project boundary"]);

boundaries.reactor = item( ...
    1443.27, "T_in", ["T_out" "m_dot_Li"], ...
    "Thesis Table 5.2 direct temperature", ...
    "✅ thesis direct");

boundaries.TAC = item( ...
    [1.539e6 1522.96 405.16 0.658e6 11.97 1000e3], ...
    ["P_in_Turbine" "T_in_Turbine" "T_in_Compressor" ...
     "p_in_Compressor" "m_in_Compressor" "Pload"], ...
    ["P_out_Turbine" "mdot_Turbine" "T_out_Turbine" ...
     "T_out_Compressor" "m_out_Compressor" "p_out_Compressor"], ...
    ["Thesis Table 5.2 direct pressure" ...
     "Thesis Table 5.2 direct temperature" ...
     "Thesis Table 5.2 direct temperature" ...
     "Thesis Table 5.2 direct pressure" ...
     "Approved project He-Xe mass-flow boundary" ...
     "Section 5.3.1 nominal load boundary; not a measured generation signal"], ...
    ["✅ thesis direct" "✅ thesis direct" "✅ thesis direct" ...
     "✅ thesis direct" "❓ project boundary" "❓ project boundary"]);
end

function value = item(inputs, inputNames, outputNames, source, evidenceGrade)
value = struct( ...
    "inputs", double(inputs), ...
    "inputNames", string(inputNames), ...
    "outputNames", string(outputNames), ...
    "source", string(source), ...
    "evidenceGrade", string(evidenceGrade));
end
