function tests = test_analyze_task8_h2a_he_third_virial_counterfactual
%TEST_ANALYZE_TASK8_H2A_HE_THIRD_VIRIAL_COUNTERFACTUAL H2a Task 1 contract.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
testCase.TestData.originalPath = path;
addpath(fullfile(root, "tests", "steady53"));
testCase.TestData.root = string(root);
testCase.TestData.options = validTestOptions(root);
testCase.TestData.protectedBefore = protectedHashes( ...
    testCase.TestData.options);
testCase.TestData.outputDir = string(fullfile(root, "tmp", "steady53", ...
    "task8_root_cause", "h2a", ...
    "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3"));
assert(~isfolder(testCase.TestData.outputDir), ...
    "The fixed H2a output directory must not pre-exist in Task 1.");
end

function teardownOnce(testCase)
path(testCase.TestData.originalPath);
assert(~isfolder(testCase.TestData.outputDir), ...
    "Task 1 must not create the fixed H2a output directory.");
end

function testFixedContractReturnsReadOnlySkeleton(testCase)
analysis = analyze_task8_h2a_he_third_virial_counterfactual();

required = sort(["inputs" "sourceAudit" "approval" "baselineParity" ...
    "exceptionPoint" "fixedPressureSweep" "h1aPathSweep" ...
    "counterfactualVerdict"]);
verifyEqual(testCase, sort(string(fieldnames(analysis))).', required);
verifyEqual(testCase, analysis.inputs.runId, ...
    "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3");
verifyEqual(testCase, analysis.inputs.exceptionT_K, ...
    992.38742737169468, "AbsTol", 1e-12);
verifyEqual(testCase, analysis.inputs.exceptionP_Pa, ...
    1007910.8613125964, "AbsTol", 1e-6);

verifyEqual(testCase, analysis.approval.scheme, "A");
verifyEqual(testCase, analysis.approval.variant, ...
    "ignoreHePureThirdVirialBeforeCurrentMixingRule");
verifyEqual(testCase, analysis.approval.pureHeliumThirdVirialTerm, "C111");
verifyEqual(testCase, analysis.approval.pureHeliumThirdVirialTreatment, ...
    "setToZero");
verifyEqual(testCase, analysis.approval.treatmentStage, ...
    "beforeCurrentMixingRule");
verifyEqual(testCase, analysis.approval.currentMixingRule, "unchanged");
verifyEqual(testCase, analysis.approval.allOtherPropertyTerms, "unchanged");
verifyFalse(testCase, analysis.approval.authorizesRepair);
verifyFalse(testCase, analysis.approval.loadsOrSimulatesSlx);
verifyFalse(testCase, analysis.approval.publishesArtifacts);

verifyEqual(testCase, analysis.baselineParity.status, ...
    "verifiedReadOnlyAgainstApprovedH2");
verifyEqual(testCase, analysis.baselineParity.evidenceGrade, "✅");
verifyTrue(testCase, analysis.baselineParity.runIdMatches);
verifyTrue(testCase, analysis.baselineParity.exceptionPointMatches);
verifyTrue(testCase, analysis.baselineParity.protectedAssetsUnchanged);

notComputedFields = ["exceptionPoint" "fixedPressureSweep" ...
    "h1aPathSweep" "counterfactualVerdict"];
for index = 1:numel(notComputedFields)
    section = analysis.(notComputedFields(index));
    verifyEqual(testCase, section.status, "notComputedInTask1");
    verifyEqual(testCase, section.evidenceGrade, "❓");
end
end

function testSourceAuditContainsEveryApprovedIdentity(testCase)
analysis = analyze_task8_h2a_he_third_virial_counterfactual();
audit = analysis.sourceAudit;

expected = expectedHashes();
names = string(fieldnames(expected));
for index = 1:numel(names)
    verifyEqual(testCase, audit.(names(index)), expected.(names(index)));
end
verifyEqual(testCase, audit.archiveTag, ...
    "archive/pre-restart-20260824");
verifyEqual(testCase, audit.archivePeeledCommit, ...
    "8f625c268c35a95c18a626305c1aa6a79ae2ace7");
verifyEqual(testCase, audit.resolvedH2AnalyzerPath, ...
    string(fullfile(testCase.TestData.root, "tests", "steady53", ...
    "analyze_task8_h2_hexe_property_readonly.m")));
verifyEqual(testCase, audit.approvedH2Outputs.csv.path, ...
    testCase.TestData.options.approvedH2CsvPath);
verifyEqual(testCase, audit.approvedH2Outputs.csv.sha256, ...
    expected.approvedH2CsvSha256);
verifyEqual(testCase, audit.approvedH2Outputs.txt.path, ...
    testCase.TestData.options.approvedH2TxtPath);
verifyEqual(testCase, audit.approvedH2Outputs.txt.sha256, ...
    expected.approvedH2TxtSha256);
verifyEqual(testCase, audit.protectedAssetHashesBefore, ...
    testCase.TestData.protectedBefore);
verifyEqual(testCase, audit.protectedAssetHashesAfter, ...
    testCase.TestData.protectedBefore);
verifyFalse(testCase, isfolder(testCase.TestData.outputDir));
end

function testPairedPathAndHashReplacementFailsClosed(testCase)
options = testCase.TestData.options;
options.compressorMatPath = options.radiatorMatPath;
options.expectedCompressorMatSha256 = options.expectedRadiatorMatSha256;
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aCompressorMatPathMismatch");
verifyFalse(testCase, isfolder(testCase.TestData.outputDir));

options = testCase.TestData.options;
options.approvedH2CsvPath = options.modelPath;
options.expectedApprovedH2CsvSha256 = options.expectedModelSha256;
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aApprovedH2CsvPathMismatch");
verifyFalse(testCase, isfolder(testCase.TestData.outputDir));
end

function testH2AnalyzerResolutionMismatchFailsClosed(testCase)
options = testCase.TestData.options;
options.h2AnalyzerResolutionProbe = string(fullfile( ...
    testCase.TestData.root, "tests", "steady53", "not_the_h2_analyzer.m"));
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aH2AnalyzerResolutionMismatch");
verifyFalse(testCase, isfolder(testCase.TestData.outputDir));
end

function testAnalyzerSourceIsStaticallyReadOnly(testCase)
sourcePath = fullfile(testCase.TestData.root, "tests", "steady53", ...
    "analyze_task8_h2a_he_third_virial_counterfactual.m");
source = fileread(sourcePath);

forbiddenModelApis = regexp(source, ...
    '(?<![A-Za-z0-9_])(set_param|sim|load_system|save_system|open_system|bdclose)\s*\(', ...
    'match');
verifyEmpty(testCase, forbiddenModelApis);
forbiddenWriters = regexp(source, ...
    '(?<![A-Za-z0-9_])(save|writetable|writecell|writematrix|fopen|copyfile|movefile|mkdir|rmdir|delete)\s*\(', ...
    'match');
verifyEmpty(testCase, forbiddenWriters);
verifyEmpty(testCase, regexp(source, ...
    '(?<![A-Za-z0-9_])load\s*\(', 'match'));
verifyNotEmpty(testCase, regexp(source, ...
    'analyze_task8_h2_hexe_property_readonly\s*\(', 'once'));
end

function testPartialOrUnknownTestOnlyOverridesFailClosed(testCase)
partial = struct("testOnly", true);
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(partial), ...
    "steady53:H2aInvalidOptions");

unknown = testCase.TestData.options;
unknown.unapprovedField = true;
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(unknown), ...
    "steady53:H2aInvalidOptions");
end

function testRunAndExceptionIdentitiesFailClosed(testCase)
options = testCase.TestData.options;
options.runId = "wrong_run";
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aRunIdMismatch");

options = testCase.TestData.options;
options.exceptionT_K = options.exceptionT_K + 1;
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aExceptionPointMismatch");

options = testCase.TestData.options;
options.exceptionP_Pa = options.exceptionP_Pa + 1;
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aExceptionPointMismatch");
end

function testEveryProtectedHashIdentityFailsClosed(testCase)
cases = {
    "expectedModelSha256", "steady53:H2aModelHashMismatch"
    "expectedPropertySha256", "steady53:H2aPropertyHashMismatch"
    "expectedCompressorMatSha256", "steady53:H2aCompressorMatHashMismatch"
    "expectedRadiatorMatSha256", "steady53:H2aRadiatorMatHashMismatch"
    "expectedTurbine1MatSha256", "steady53:H2aTurbine1MatHashMismatch"
    "expectedTurbine2MatSha256", "steady53:H2aTurbine2MatHashMismatch"
    "expectedInputMatSha256", "steady53:H2aInputMatHashMismatch"
    "expectedThesisPdfSha256", "steady53:H2aThesisPdfHashMismatch"
    "expectedApprovedH2CsvSha256", "steady53:H2aApprovedH2CsvHashMismatch"
    "expectedApprovedH2TxtSha256", "steady53:H2aApprovedH2TxtHashMismatch"
    };
for index = 1:size(cases, 1)
    options = testCase.TestData.options;
    options.(cases{index, 1}) = string(repmat('0', 1, 64));
    verifyError(testCase, ...
        @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
        cases{index, 2});
end
end

function testArchiveIdentitiesFailClosed(testCase)
options = testCase.TestData.options;
options.archiveTag = "archive/not-approved";
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aArchiveTagMismatch");

options = testCase.TestData.options;
options.expectedArchivePeeledCommit = string(repmat('0', 1, 40));
verifyError(testCase, ...
    @() analyze_task8_h2a_he_third_virial_counterfactual(options), ...
    "steady53:H2aArchiveCommitMismatch");
end

function options = validTestOptions(root)
runId = "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3";
h2Dir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h2", runId);
options = struct();
options.testOnly = true;
options.runId = runId;
options.exceptionT_K = 992.38742737169468;
options.exceptionP_Pa = 1007910.8613125964;
options.modelPath = string(fullfile(root, "final_steady_24a.slx"));
options.expectedModelSha256 = ...
    "5423af38d6bbfc7730529475a6c4d046ef1386ec56782ba465c87dfae82cbf5d";
options.propertyPath = string(fullfile(root, "HeXe_property_simulink.m"));
options.expectedPropertySha256 = ...
    "2490785cba7ae3d1f9bb4d4e52621f7b925945aab0f4f93e1a71b504783f5cf2";
options.compressorMatPath = string(fullfile(root, "hexe_compressor_lookup.mat"));
options.expectedCompressorMatSha256 = ...
    "f9c85bc1ae831333fac5f868f15a6f82ea1c1716ee17f23dfb301f4618c9f579";
options.radiatorMatPath = string(fullfile(root, "radiator_table.mat"));
options.expectedRadiatorMatSha256 = ...
    "3f6e8a08f6ec9253b84d07f8eff11d2b093f785bafcfde515f2c6af4ec263304";
options.turbine1MatPath = string(fullfile(root, "turbine_table1.mat"));
options.expectedTurbine1MatSha256 = ...
    "10e72638374c530e2032d9bfe39b060d4181b0467bf69e03196efa0b90c4971d";
options.turbine2MatPath = string(fullfile(root, "turbine_table2.mat"));
options.expectedTurbine2MatSha256 = ...
    "cda85dc4480a7723a0ef52bda0fb6f2795e14dfe1167ac74b38a8d64d5b58c33";
options.inputMatPath = string(fullfile(root, "tmp", "steady53", "task8", ...
    runId, "nominal_500_report.mat"));
options.expectedInputMatSha256 = ...
    "4ea018c7be06c5e577f107970dc2bf549924bf7a9a2989a89bcf1be76e98472b";
options.thesisPdfPath = string(fullfile( ...
    "/Users/ikunsredemptionmac/Downloads/不接入转子稳态模型", ...
    "空间锂冷堆He-Xe布雷顿循环发电系统优化设计与运行特性分析_徐驰.pdf"));
options.expectedThesisPdfSha256 = ...
    "983bfc23712221f30202a47875cbe34c9559edf79b9c332aa20931b6075e4e7a";
options.approvedH2CsvPath = string(fullfile(h2Dir, ...
    "h2_property_diagnostics.csv"));
options.expectedApprovedH2CsvSha256 = ...
    "b2998bdafd96cdd49d9fa4ff621dc586add229dd525a9d0d79a7c22fc71ee9d6";
options.approvedH2TxtPath = string(fullfile(h2Dir, "h2_summary.txt"));
options.expectedApprovedH2TxtSha256 = ...
    "1fa29cebd816d891fecddfa8c54863d1f672f44a8793cb6e32cf3084241f9799";
options.archiveTag = "archive/pre-restart-20260824";
options.expectedArchivePeeledCommit = ...
    "8f625c268c35a95c18a626305c1aa6a79ae2ace7";
options.h2AnalyzerResolutionProbe = string(fullfile(root, "tests", ...
    "steady53", "analyze_task8_h2_hexe_property_readonly.m"));
end

function expected = expectedHashes()
expected = struct( ...
    "modelSha256", ...
        "5423af38d6bbfc7730529475a6c4d046ef1386ec56782ba465c87dfae82cbf5d", ...
    "propertySha256", ...
        "2490785cba7ae3d1f9bb4d4e52621f7b925945aab0f4f93e1a71b504783f5cf2", ...
    "compressorMatSha256", ...
        "f9c85bc1ae831333fac5f868f15a6f82ea1c1716ee17f23dfb301f4618c9f579", ...
    "radiatorMatSha256", ...
        "3f6e8a08f6ec9253b84d07f8eff11d2b093f785bafcfde515f2c6af4ec263304", ...
    "turbine1MatSha256", ...
        "10e72638374c530e2032d9bfe39b060d4181b0467bf69e03196efa0b90c4971d", ...
    "turbine2MatSha256", ...
        "cda85dc4480a7723a0ef52bda0fb6f2795e14dfe1167ac74b38a8d64d5b58c33", ...
    "inputMatSha256", ...
        "4ea018c7be06c5e577f107970dc2bf549924bf7a9a2989a89bcf1be76e98472b", ...
    "thesisPdfSha256", ...
        "983bfc23712221f30202a47875cbe34c9559edf79b9c332aa20931b6075e4e7a", ...
    "approvedH2CsvSha256", ...
        "b2998bdafd96cdd49d9fa4ff621dc586add229dd525a9d0d79a7c22fc71ee9d6", ...
    "approvedH2TxtSha256", ...
        "1fa29cebd816d891fecddfa8c54863d1f672f44a8793cb6e32cf3084241f9799");
end

function hashes = protectedHashes(options)
name = ["model"; "property"; "compressorMat"; "radiatorMat"; ...
    "turbine1Mat"; "turbine2Mat"; "inputMat"; "thesisPdf"; ...
    "approvedH2Csv"; "approvedH2Txt"];
pathValue = [options.modelPath; options.propertyPath; ...
    options.compressorMatPath; options.radiatorMatPath; ...
    options.turbine1MatPath; options.turbine2MatPath; ...
    options.inputMatPath; options.thesisPdfPath; ...
    options.approvedH2CsvPath; options.approvedH2TxtPath];
sha256 = strings(numel(pathValue), 1);
for index = 1:numel(pathValue)
    sha256(index) = sha256File(pathValue(index));
end
hashes = table(name, pathValue, sha256);
end

function hash = sha256File(filePath)
[status, output] = system("shasum -a 256 " + shellQuote(filePath));
assert(status == 0, "Hash failed: %s", output);
parts = split(strtrim(string(output)));
hash = lower(parts(1));
end

function quoted = shellQuote(value)
quoted = "'" + replace(string(value), "'", "'\''") + "'";
end
