function tests = test_analyze_task8_h1b_cpbar_readonly
%TEST_ANALYZE_TASK8_H1B_CPBar_READONLY Fixed-evidence H1b analyzer contract.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = fileparts(fileparts(fileparts(mfilename("fullpath"))));
testCase.TestData.originalPath = path;
testCase.TestData.originalWarnings = warning;
addpath(root, "-begin");
addpath(fullfile(root, "tests", "steady53"), "-begin");
testCase.TestData.root = string(root);
testCase.TestData.tempRoot = string(tempname);
mkdir(testCase.TestData.tempRoot);
testCase.TestData.loadedBefore = loadedBlockDiagrams();
testCase.TestData.protectedBefore = protectedHashes(root);
end

function teardownOnce(testCase)
path(testCase.TestData.originalPath);
warning(testCase.TestData.originalWarnings);
if isfolder(testCase.TestData.tempRoot)
    rmdir(testCase.TestData.tempRoot, "s");
end
end

function testRealFormalPropertyComputesAllThreeCandidates(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "real_h1b");
analysis = analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir)));
verifyEqual(testCase, analysis.runId, ...
    "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3");
verifyEqual(testCase, sort(string({analysis.candidates.pathVariant})), ...
    sort(["linearEndpointPressure" "constantP1" "constantP2"]));
verifyEqual(testCase, analysis.inputs.T2s_K, ...
    1089.5635709913104, "AbsTol", 1e-12);
verifyEqual(testCase, analysis.inputs.eta, ...
    0.87286960881076081, "AbsTol", 1e-15);
verifyLessThanOrEqual(testCase, ...
    abs(analysis.h1aPointCpReproductionResidual_K), 1e-9);
for candidate = analysis.candidates
    verifyTrue(testCase, candidate.integrationCompleted);
    verifyTrue(testCase, candidate.rootConverged);
    verifyLessThanOrEqual(testCase, abs(candidate.rootResidual_K), 1e-9);
    verifyTrue(testCase, candidate.actualPathAudit.allPhysical);
    verifyTrue(testCase, candidate.idealPathAudit.allPhysical);
end
verifyTrue(testCase, analysis.h1bExecuted);
verifyFalse(testCase, analysis.h1bPressurePathSelectedAsFormal);
verifyFalse(testCase, analysis.authorizesRepair);
verifyFalse(testCase, analysis.formalModelPromotion);
verifyFalse(testCase, analysis.slxLoadedOrSimulated);
end

function testBaselineIdentityAndSingleVariableScope(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "scope_identity");
analysis = analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir)));
expected = expectedHashes();
verifyEqual(testCase, analysis.hashes, expected);
verifyEqual(testCase, analysis.archiveCommit, ...
    "8f625c268c35a95c18a626305c1aa6a79ae2ace7");
verifyEqual(testCase, analysis.scope.h1aPhiPropertyVariant, "schemeA");
verifyEqual(testCase, analysis.scope.h1bCpbarPropertyVariant, ...
    "formalHeXeProperty");
verifyTrue(testCase, analysis.scope.T2sHeldFixed);
verifyTrue(testCase, analysis.scope.etaHeldFixed);
verifyTrue(testCase, analysis.scope.onlyPointCpReplacedByPathCpbar);
verifyTrue(testCase, analysis.h1aCandidateBaselineSelectedForExperiment);
verifyFalse(testCase, analysis.h1aCandidateBaselinePromotedToFormalModel);
verifyEqual(testCase, analysis.inputs.phiBar, ...
    0.39979002315209694, "AbsTol", 1e-15);
verifyEqual(testCase, analysis.inputs.T2s_K, ...
    1089.5635709913104, "AbsTol", 1e-12);
verifyEqual(testCase, analysis.h1aCandidateT2_K, ...
    1143.6624955393854, "AbsTol", 1e-12);
end

function testOutputIsIndependentlySelfContained(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "self_contained");
analysis = analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir)));
entries = dir(outputDir);
entries = entries(~ismember(string({entries.name}), ["." ".."])) ;
verifyEqual(testCase, sort(string({entries.name})).', ...
    ["h1b_cpbar_sensitivity.csv"; "h1b_cpbar_summary.txt"]);
verifyFalse(testCase, any([entries.isdir]));
verifyEqual(testCase, sha256File(analysis.csvPath), analysis.csvSha256);
verifyEqual(testCase, sha256File(analysis.summaryPath), ...
    analysis.summarySha256);

csv = readtable(analysis.csvPath, "TextType", "string", ...
    "VariableNamingRule", "preserve");
csvText = string(fileread(analysis.csvPath));
verifyTrue(testCase, contains(csvText, "519.6587987339517"));
verifyTrue(testCase, contains(csvText, "1143.6619213135946"));
verifyEqual(testCase, height(csv), 4);
verifyEqual(testCase, sort(csv.method), sort([ ...
    "H1a_S2_schemeA_pointCp_baseline"
    "H1b_linearEndpointPressure"
    "H1b_constantP1"
    "H1b_constantP2"]));
requiredColumns = [ ...
    "method" "pathVariant" "runId" "inputMat" "inputMatSha256" ...
    "formalModel" "modelSha256" "formalProperty" ...
    "formalPropertySha256" "turbineTable" "turbineTableSha256" ...
    "schemeAHelper" "schemeAHelperSha256" "h1aCsv" ...
    "h1aCsvSha256" "h1aTxt" "h1aTxtSha256" "h2aCsv" ...
    "h2aCsvSha256" "h2aTxt" "h2aTxtSha256" "archiveCommit" ...
    "h1aPhiPropertyVariant" "h1bCpbarPropertyVariant" ...
    "T2sHeldFixed" "etaHeldFixed" ...
    "onlyPointCpReplacedByPathCpbar" "T1_K" "P1_Pa" "P2_Pa" ...
    "T2s_K" "eta" "phiBar" "h1aCandidateT2_K" "targetT2_K" ...
    "pointCp1_J_kgK" "pointCp2s_J_kgK" ...
    "pathIntegralApplicable" "cpBarIsentropic_J_kgK" ...
    "cpBarActual_J_kgK" "cpBarRatio" "T2_K" ...
    "deltaT2FromH1a_K" "remainingTargetError_K" ...
    "explainedFractionOfH1aGap" "targetDirectionMatched" ...
    "h1bNumericallySufficient" "integrationCompleted" ...
    "rootConverged" "rootResidual_K" ...
    "idealPathAuditSampleCount" "actualPathAuditSampleCount" ...
    "idealPathAuditAllPhysical" "actualPathAuditAllPhysical" ...
    "idealPathAuditFormalGlobalProof" ...
    "actualPathAuditFormalGlobalProof" ...
    "h1aCandidateBaselineSelectedForExperiment" ...
    "h1aCandidateBaselinePromotedToFormalModel" "h1bExecuted" ...
    "h1bPressurePathSelectedAsFormal" "modelModified" ...
    "formalPropertyModified" "slxLoadedOrSimulated" ...
    "authorizesRepair" "formalModelPromotion" "task8Passed" ...
    "steady14000AcceptancePassed"];
verifyTrue(testCase, all(ismember(requiredColumns, ...
    string(csv.Properties.VariableNames))));
verifyEqual(testCase, unique(csv.runId), analysis.runId);
verifyEqual(testCase, unique(csv.h1aCsvSha256), ...
    expectedHashes().h1aCsvSha256);
verifyEqual(testCase, unique(csv.h1bCpbarPropertyVariant), ...
    "formalHeXeProperty");
verifyTrue(testCase, all(csv.T2sHeldFixed));
verifyTrue(testCase, all(csv.etaHeldFixed));
verifyTrue(testCase, all(csv.onlyPointCpReplacedByPathCpbar));
baseline = csv(csv.method == "H1a_S2_schemeA_pointCp_baseline", :);
verifyEqual(testCase, baseline.pathIntegralApplicable, 0);
verifyTrue(testCase, ismissing(baseline.cpBarActual_J_kgK));
h1b = csv(startsWith(csv.method, "H1b_"), :);
verifyTrue(testCase, all(h1b.pathIntegralApplicable));
finiteColumns = ["cpBarIsentropic_J_kgK" "cpBarActual_J_kgK" ...
    "cpBarRatio" "T2_K" "deltaT2FromH1a_K" ...
    "remainingTargetError_K" "explainedFractionOfH1aGap"];
for column = finiteColumns
    verifyTrue(testCase, all(isfinite(h1b.(column))));
end
verifyTrue(testCase, all(h1b.idealPathAuditSampleCount == 1001));
verifyTrue(testCase, all(h1b.actualPathAuditSampleCount == 1001));
verifyTrue(testCase, all(h1b.idealPathAuditAllPhysical));
verifyTrue(testCase, all(h1b.actualPathAuditAllPhysical));
verifyFalse(testCase, any(h1b.idealPathAuditFormalGlobalProof));
verifyFalse(testCase, any(h1b.actualPathAuditFormalGlobalProof));

summary = string(fileread(analysis.summaryPath));
requiredText = [ ...
    "runId="+analysis.runId
    "equation=R(T2)=T2-[T1-eta*(cpBarIsentropic/cpBarActual)*(T1-T2s)]"
    "linearEndpointPressure=P1+lambda*(P2-P1)"
    "constantP1=P1"
    "constantP2=P2"
    "h1aPhiPropertyVariant=schemeA"
    "h1bCpbarPropertyVariant=formalHeXeProperty"
    "onlyPointCpReplacedByPathCpbar=true"
    "h1bPressurePathSelectedAsFormal=false"
    "formalGlobalProof=false"
    "slxLoadedOrSimulated=false"
    "authorizesRepair=false"];
for item = requiredText
    verifyTrue(testCase, contains(summary, item));
end
for hash = string(struct2cell(expectedHashes())).'
    verifyTrue(testCase, contains(summary, hash));
end
end

function testH1aHashMismatchPrecedesOutputCreation(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "h1a_hash_mismatch");
control = completeTestControl(testCase.TestData.root, outputDir);
control.expectedH1aCsvSha256 = string(repmat('0', 1, 64));
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bH1aEvidenceHashMismatch");
verifyFalse(testCase, isfolder(outputDir));
end

function testMalformedH1aEvidenceFailsClosed(testCase)
ownedDir = fullfile(testCase.TestData.tempRoot, "malformed_h1a_inputs");
mkdir(ownedDir);
control = completeTestControl(testCase.TestData.root, ...
    fullfile(testCase.TestData.tempRoot, "malformed_h1a_output"));
copiedCsv = fullfile(ownedDir, "h1a_sensitivity.csv");
copiedTxt = fullfile(ownedDir, "h1a_summary.txt");
copyfile(control.h1aCsvPath, copiedCsv);
copyfile(control.h1aTxtPath, copiedTxt);
tableValue = readtable(copiedCsv, "TextType", "string", ...
    "VariableNamingRule", "preserve");
tableValue = [tableValue; tableValue(end, :)];
writetable(tableValue, copiedCsv);
control.h1aCsvPath = string(copiedCsv);
control.expectedH1aCsvSha256 = sha256File(copiedCsv);
control.h1aTxtPath = string(copiedTxt);
control.expectedH1aTxtSha256 = sha256File(copiedTxt);
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bInvalidH1aEvidence");
verifyFalse(testCase, isfolder(control.outputDir));
end

function testH1aPointBaselineMismatchFailsClosed(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "baseline_mismatch");
control = completeTestControl(testCase.TestData.root, outputDir);
control.propertyFunction = @shiftedFormalProperty;
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bBaselineMismatch");
verifyFalse(testCase, isfolder(outputDir));
end

function testProtectedDependencyHashMismatchFailsClosed(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "protected_mismatch");
control = completeTestControl(testCase.TestData.root, outputDir);
control.expectedModelSha256 = string(repmat('f', 1, 64));
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bProtectedHashMismatch");
verifyFalse(testCase, isfolder(outputDir));
end

function testExistingOutputRefusesOverwrite(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "existing_output");
mkdir(outputDir);
sentinel = fullfile(outputDir, "sentinel.txt");
fileId = fopen(sentinel, "w");
assert(fileId >= 0);
fprintf(fileId, "do not overwrite\n");
fclose(fileId);
sentinelHash = sha256File(sentinel);
verifyError(testCase, @() analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir))), ...
    "steady53:H1bOutputExists");
verifyEqual(testCase, sha256File(sentinel), sentinelHash);
verifyFalse(testCase, isfile(fullfile(outputDir, ...
    "h1b_cpbar_sensitivity.csv")));
verifyEmpty(testCase, stagingDirectories(outputDir));
end

function testTransactionalPublicationLeavesNoHalfOutput(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "transaction_failure");
control = completeTestControl(testCase.TestData.root, outputDir);
control.outputFailureHook = @failAfterCsv;
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bOutputFailed");
verifyFalse(testCase, isfolder(outputDir));
verifyEmpty(testCase, stagingDirectories(outputDir));
end

function testUnknownOrPartialOverrideFailsClosed(testCase)
outputDir = fullfile(testCase.TestData.tempRoot, "invalid_options");
verifyError(testCase, @() analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir), ...
    "extra", true)), "steady53:H1bInvalidOptions");
control = completeTestControl(testCase.TestData.root, outputDir);
partial = rmfield(control, "expectedH1aCsvSha256");
verifyError(testCase, @() analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "testControl", partial)), ...
    "steady53:H1bInvalidOptions");
control.extra = true;
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bInvalidOptions");
verifyFalse(testCase, isfolder(outputDir));
end

function testEnvironmentAndLoadedDiagramsArePreserved(testCase)
pathBefore = path;
warningsBefore = warning;
diagramsBefore = loadedBlockDiagrams();
hashesBefore = protectedHashes(testCase.TestData.root);
outputDir = fullfile(testCase.TestData.tempRoot, "environment_success");
analysis = analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "outputDir", string(outputDir)));
verifyEqual(testCase, path, pathBefore);
verifyEqual(testCase, warning, warningsBefore);
verifyEqual(testCase, loadedBlockDiagrams(), diagramsBefore);
verifyEqual(testCase, protectedHashes(testCase.TestData.root), hashesBefore);
verifyTrue(testCase, analysis.propertyStateCanonicalCleared);

failedOutput = fullfile(testCase.TestData.tempRoot, "environment_failure");
control = completeTestControl(testCase.TestData.root, failedOutput);
control.expectedH2aTxtSha256 = string(repmat('0', 1, 64));
verifyError(testCase, @() analyzeWithControl(control), ...
    "steady53:H1bProtectedHashMismatch");
verifyEqual(testCase, path, pathBefore);
verifyEqual(testCase, warning, warningsBefore);
verifyEqual(testCase, loadedBlockDiagrams(), diagramsBefore);
verifyEqual(testCase, protectedHashes(testCase.TestData.root), hashesBefore);
verifyFalse(testCase, isfolder(failedOutput));
end

function testAnalyzerContainsNoModelApis(testCase)
root = testCase.TestData.root;
files = [ ...
    fullfile(root, "tests", "steady53", ...
        "h1b_cpbar_candidate_readonly.m")
    fullfile(root, "tests", "steady53", ...
        "analyze_task8_h1b_cpbar_readonly.m")];
pattern = ['(?<![A-Za-z0-9_])' ...
    '(load_system|open_system|sim|set_param|save_system|bdclose)\s*\('];
for file = files.'
    source = string(fileread(file));
    verifyEmpty(testCase, regexp(source, pattern, "match"));
end
analyzerSource = string(fileread(files(2)));
required = [ ...
    "HeXe_property_simulink"
    "h1b_cpbar_candidate_readonly"
    "linearEndpointPressure"
    "constantP1"
    "constantP2"
    string(struct2cell(expectedHashes()))];
for item = required
    verifyTrue(testCase, contains(analyzerSource, item));
end
end

function analysis = analyzeWithControl(control)
analysis = analyze_task8_h1b_cpbar_readonly( ...
    struct("testOnly", true, "testControl", control));
end

function control = completeTestControl(root, outputDir)
runId = "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3";
h1aDir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h1a_s2_scheme_a", runId);
h2aDir = fullfile(root, "tmp", "steady53", "task8_root_cause", ...
    "h2a", runId);
hashes = expectedHashes();
control = struct( ...
    "runId", runId, ...
    "inputMat", string(fullfile(root, "tmp", "steady53", "task8", ...
        runId, "nominal_500_report.mat")), ...
    "expectedInputSha256", hashes.inputMatSha256, ...
    "modelPath", string(fullfile(root, "final_steady_24a.slx")), ...
    "expectedModelSha256", hashes.modelSha256, ...
    "formalPropertyPath", string(fullfile(root, ...
        "HeXe_property_simulink.m")), ...
    "expectedFormalPropertySha256", hashes.formalPropertySha256, ...
    "turbineTableMat", string(fullfile(root, "turbine_table2.mat")), ...
    "expectedTurbineTableSha256", hashes.turbineTableSha256, ...
    "schemeAHelperPath", string(fullfile(root, "tests", "steady53", ...
        "hexe_property_scheme_a_offline.m")), ...
    "expectedSchemeAHelperSha256", hashes.schemeAHelperSha256, ...
    "h1aCsvPath", string(fullfile(h1aDir, "h1a_sensitivity.csv")), ...
    "expectedH1aCsvSha256", hashes.h1aCsvSha256, ...
    "h1aTxtPath", string(fullfile(h1aDir, "h1a_summary.txt")), ...
    "expectedH1aTxtSha256", hashes.h1aTxtSha256, ...
    "h2aCsvPath", string(fullfile(h2aDir, ...
        "h2a_counterfactual_diagnostics.csv")), ...
    "expectedH2aCsvSha256", hashes.h2aCsvSha256, ...
    "h2aTxtPath", string(fullfile(h2aDir, "h2a_summary.txt")), ...
    "expectedH2aTxtSha256", hashes.h2aTxtSha256, ...
    "archiveRef", "archive/pre-restart-20260824^{}", ...
    "expectedArchiveCommit", ...
        "8f625c268c35a95c18a626305c1aa6a79ae2ace7", ...
    "propertyFunction", @HeXe_property_simulink, ...
    "pathVariants", ["linearEndpointPressure" "constantP1" "constantP2"], ...
    "numerics", fixedNumerics(), ...
    "outputDir", string(outputDir), ...
    "outputFailureHook", @noOutputFailure);
end

function hashes = expectedHashes()
hashes = struct( ...
    "h1aCsvSha256", ...
        "7e1ed139d14cbb1977a9f19d870c822243205414321a00c0f597717f5616f622", ...
    "h1aTxtSha256", ...
        "26248e95f42acbb70701193fa75af429b60659b9975277837331b8cd2803efd2", ...
    "inputMatSha256", ...
        "4ea018c7be06c5e577f107970dc2bf549924bf7a9a2989a89bcf1be76e98472b", ...
    "modelSha256", ...
        "5423af38d6bbfc7730529475a6c4d046ef1386ec56782ba465c87dfae82cbf5d", ...
    "formalPropertySha256", ...
        "2490785cba7ae3d1f9bb4d4e52621f7b925945aab0f4f93e1a71b504783f5cf2", ...
    "turbineTableSha256", ...
        "cda85dc4480a7723a0ef52bda0fb6f2795e14dfe1167ac74b38a8d64d5b58c33", ...
    "schemeAHelperSha256", ...
        "5820e957b90b1affce777c1774aee6cc685f40430310408fb00f303846f606d0", ...
    "h2aCsvSha256", ...
        "6a8398b7a32685cb3d198a1fe39b3b9365cfdefe65143d5613c68ffdd44366f4", ...
    "h2aTxtSha256", ...
        "afd75b1b31cd0abdbdb2926b95ab987f260caa81a55fe2e901fdde4dafd72465");
end

function numerics = fixedNumerics()
numerics = struct("integralFunction", @integral, ...
    "rootFunction", @fzero, "integralRelTol", 1e-8, ...
    "integralAbsTol_J_kgK", 1e-8, "rootTolX_K", 1e-12, ...
    "rootMaxIterations", 1000, ...
    "rootMaxFunctionEvaluations", 5000, ...
    "rootAbsResidualTolerance_K", 1e-9, "auditSampleCount", 1001);
end

function [cp, gamma, rho] = shiftedFormalProperty(T_K, P_Pa)
[cp, gamma, rho] = HeXe_property_simulink(T_K, P_Pa);
cp = cp*(1+1e-4*T_K/1500);
end

function failAfterCsv(point, ~)
if point == "afterCsvBeforeSummary"
    error("tests:H1bControlledOutputFailure", ...
        "Synthetic failure after staged CSV publication.");
end
end

function noOutputFailure(~, ~)
end

function entries = stagingDirectories(outputDir)
[parentDir, outputName, outputExtension] = fileparts(outputDir);
prefix = "."+string(outputName)+string(outputExtension)+".staging_";
listing = dir(fullfile(parentDir, prefix+"*"));
entries = string({listing.name});
end

function diagrams = loadedBlockDiagrams()
diagrams = sort(string(find_system("type", "block_diagram")));
diagrams = diagrams(:);
end

function hashes = protectedHashes(root)
paths = [ ...
    string(fullfile(root, "final_steady_24a.slx"))
    string(fullfile(root, "HeXe_property_simulink.m"))
    string(fullfile(root, "turbine_table2.mat"))
    string(fullfile(root, "tmp", "steady53", "task8", ...
        "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3", ...
        "nominal_500_report.mat"))
    string(fullfile(root, "tests", "steady53", ...
        "hexe_property_scheme_a_offline.m"))
    string(fullfile(root, "tmp", "steady53", "task8_root_cause", ...
        "h1a_s2_scheme_a", ...
        "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3", ...
        "h1a_sensitivity.csv"))
    string(fullfile(root, "tmp", "steady53", "task8_root_cause", ...
        "h1a_s2_scheme_a", ...
        "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3", ...
        "h1a_summary.txt"))
    string(fullfile(root, "tmp", "steady53", "task8_root_cause", ...
        "h2a", "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3", ...
        "h2a_counterfactual_diagnostics.csv"))
    string(fullfile(root, "tmp", "steady53", "task8_root_cause", ...
        "h2a", "run_1787582761047_bb4aa60600cc4d9e9cc15077c6f435d3", ...
        "h2a_summary.txt"))];
hashes = strings(size(paths));
for index = 1:numel(paths)
    hashes(index) = sha256File(paths(index));
end
end

function hashValue = sha256File(filePath)
digest = java.security.MessageDigest.getInstance("SHA-256");
fileBytes = java.nio.file.Files.readAllBytes( ...
    java.io.File(char(filePath)).toPath());
bytes = typecast(digest.digest(fileBytes), "uint8");
hashValue = lower(join(compose("%02x", bytes), ""));
end
