function result = audit_fig519_initialization(outputDir, existingRawReference)
%AUDIT_FIG519_INITIALIZATION Read-only API audit of the frozen Figure 5.19 baseline.
%   The function creates one new exploration directory below repository tmp/,
%   inspects the immutable f8bcd83 steady model without saving.  Default mode
%   performs exactly one unmodified 500 s instrumented reference simulation;
%   the optional fixed-raw mode only regenerates compact derived evidence.

arguments
    outputDir {mustBeTextScalar}
    existingRawReference {mustBeTextScalar} = ""
end

repo = string(fileparts(fileparts(mfilename("fullpath"))));
tmpRoot = fullfile(repo, "tmp");
outputDir = validateNewOutputDirectory(outputDir, tmpRoot);
runtimeDir = fullfile(repo, "data", "provenance", "baselines", ...
    "f8bcd83", "runtime");
modelPath = fullfile(repo, "data", "provenance", "baselines", ...
    "f8bcd83", "final_steady_24a.slx");
expectedModelHash = ...
    "0532e9ddf2deb7ef5e40cc1b8e619c44ea7afd36b00d807d118f4cd812a5a391";
protectedPath = fullfile(repo, "data", "provenance", "baselines", ...
    "f8bcd83", "protected_manifest_recovery.csv");

modelHashBefore = sha256File(modelPath);
if modelHashBefore ~= expectedModelHash
    error("fig519:BaselineHashMismatch", ...
        "Frozen steady baseline hash does not match the Task 6 contract.");
end
protectedBefore = verifyProtectedManifest(protectedPath);

mkdir(outputDir);
oldFolder = string(pwd);
folderCleanup = onCleanup(@() cd(oldFolder));
% The current folder outranks addpath in MATLAB.  Move into the private
% output directory so root files with identical names cannot shadow the
% immutable f8bcd83 runtime.
cd(outputDir);
oldPath = path;
pathCleanup = onCleanup(@() path(oldPath));
addpath(runtimeDir, fullfile(repo, "tests", "steady53"));
runtimeDependencyContract = verifyRuntimeDependencies(runtimeDir);

startPath = fullfile(runtimeDir, "start.m");
startVariables = startWorkspaceVariables(startPath);
baseSnapshot = captureBaseWorkspace(startVariables);
baseCleanup = onCleanup(@() restoreBaseWorkspace(baseSnapshot));
evalin("base", "run(" + matlabString(startPath) + ")");

[~, model] = fileparts(modelPath);
model = string(model);
if bdIsLoaded(model)
    error("fig519:ModelAlreadyLoaded", ...
        "The audit refuses a preloaded model because it may contain unsaved work.");
end
modelCleanup = onCleanup(@() closeWithoutSaving(model));
load_system(modelPath);
loadedFile = string(get_param(model, "FileName"));
if string(java.io.File(loadedFile).getCanonicalPath()) ~= ...
        string(java.io.File(modelPath).getCanonicalPath())
    error("fig519:WrongModelLoaded", ...
        "load_system did not load the hash-contracted baseline path.");
end

[manifest, stateMeta] = steady53_signal_manifest(model);
if numel(stateMeta) ~= 40
    error("fig519:StateCountMismatch", ...
        "Expected 40 manifest states, found %d.", numel(stateMeta));
end
stateInitialConditions = readInitialConditions(stateMeta);
solverContract = auditSolverContract(model);
boundaryContract = auditBoundaryContract(model);
powerPaths = auditPowerPaths(model, manifest);
powerStateTraceContract = auditPowerStatePaths(model, powerPaths);
boundaryContract.load_input_classified = ...
    powerPaths.load.status == "verified_by_official_api";
boundaryContract.all_inputs_classified = ...
    boundaryContract.all_inputs_classified && ...
    boundaryContract.load_input_classified;
residualTemplates = residualContracts(model, powerPaths);
closeWithoutSaving(model);

if string(existingRawReference) == ""
    % This is the only run_steady53_case call in this function.  It is
    % justified by the absence of state and derivative evidence in the prior
    % saved baseline.
    runResult = run_steady53_case(modelPath, 500, true);
else
    runResult = loadFixedRawReference(existingRawReference, repo);
end
if ~runResult.success
    error("fig519:ReferenceRunFailed", ...
        "The unmodified reference run failed: %s\n%s", ...
        runResult.errorId, runResult.errorReport);
end
if runResult.tFinal_s ~= 500 || numel(runResult.states) ~= 40
    error("fig519:ReferenceRunIncomplete", ...
        "Reference run did not return 40 states through 500 s.");
end

inventory = buildStateInventory( ...
    stateMeta, stateInitialConditions, runResult);
initialResiduals = calculateResiduals( ...
    residualTemplates, inventory, runResult, powerPaths);
flatExplanation = explainFlatStart( ...
    inventory, runResult, powerPaths, powerStateTraceContract);

modelHashAfter = sha256File(modelPath);
protectedAfter = verifyProtectedManifest(protectedPath);
sourceHashUnchanged = modelHashAfter == modelHashBefore;
if ~sourceHashUnchanged || ~isequal(protectedBefore, protectedAfter)
    error("fig519:ProtectedSourceChanged", ...
        "The model or protected recovery manifest changed during the audit.");
end

if string(existingRawReference) == ""
    rawPath = fullfile(outputDir, "raw_reference.mat");
    save(rawPath, "runResult", "-v7.3");
else
    rawPath = string(java.io.File(existingRawReference).getCanonicalPath());
end

result = struct( ...
    "audit_schema", "steady53_fig519_initialization_v1", ...
    "model_path", relativeToRepo(modelPath, repo), ...
    "model_sha256", modelHashBefore, ...
    "source_hash_after", modelHashAfter, ...
    "source_hash_unchanged", sourceHashUnchanged, ...
    "state_count", numel(inventory), ...
    "reference_final_time_s", runResult.tFinal_s, ...
    "reference_success", runResult.success, ...
    "reference_run_reason", ...
        "missing direct state and derivative evidence in prior saved baseline", ...
    "repeated_prior_experiment", false, ...
    "direct_generator_signal_found", powerPaths.direct_generator_signal_found, ...
    "paper_reproduced", false, ...
    "formal_promotion", false, ...
    "generation_contract", struct( ...
        "schema_version", "steady53_fig519_initialization_v2_api_graph", ...
        "generator_repository_path", "tests/audit_fig519_initialization.m", ...
        "generator_sha256", sha256File(fullfile(repo, "tests", ...
            "audit_fig519_initialization.m")), ...
        "model_sha256", modelHashBefore, ...
        "raw_reference_sha256", sha256File(rawPath), ...
        "python_validation_scope", ...
            "structural, identity, exact-contract, and cross-field checks only; Python does not recompute MATLAB state values from raw_reference.mat", ...
        "matlab_evidence_scope", ...
            "state values come from fixed raw evidence; connection hops come from the Simulink official API graph"), ...
    "raw_reference", struct( ...
        "repository_relative_path", relativeToRepo(rawPath, repo), ...
        "absolute_path", string(rawPath), ...
        "sha256", sha256File(rawPath), ...
        "bytes", fileBytes(rawPath)), ...
    "protected_manifest", protectedAfter, ...
    "runtime_dependency_contract", runtimeDependencyContract, ...
    "state_inventory", inventory, ...
    "boundary_contract", boundaryContract, ...
    "solver_contract", solverContract, ...
    "power_signal_paths", powerPaths, ...
    "initial_residuals", initialResiduals, ...
    "flat_start_explanation", flatExplanation);

jsonPath = fullfile(outputDir, "initialization_audit.json");
writeExclusiveText(jsonPath, ...
    string(jsonencode(result, PrettyPrint=true)) + newline);
end

function contract = verifyRuntimeDependencies(runtimeDir)
names = ["HeXe_property_simulink.m"; "Lithium_property_simulink.m"; ...
    "hexe_compressor_lookup.mat"; "radiator_table.mat"; ...
    "turbine_table1.mat"; "turbine_table2.mat"; "paper54_constants.m"; ...
    "sys_param_rad_fixed.m"; "start.m"];
records = repmat(struct("name", "", "resolved_path", "", ...
    "sha256", "", "is_durable", false), numel(names), 1);
canonicalRuntime = string(java.io.File(runtimeDir).getCanonicalPath());
for index = 1:numel(names)
    resolved = string(which(names(index)));
    if resolved == ""
        candidate = fullfile(runtimeDir, names(index));
        if isfile(candidate)
            resolved = candidate;
        end
    end
    canonical = string(java.io.File(resolved).getCanonicalPath());
    records(index).name = names(index);
    records(index).resolved_path = canonical;
    records(index).sha256 = sha256File(canonical);
    records(index).is_durable = startsWith(canonical, canonicalRuntime + filesep);
end
contract = struct("dependency_count", numel(records), ...
    "all_paths_durable", all([records.is_durable]), ...
    "runtime_directory", canonicalRuntime, "dependencies", records);
if ~contract.all_paths_durable
    error("fig519:RuntimeDependencyShadowed", ...
        "A same-named file shadows the immutable f8bcd83 runtime.");
end
end

function outputDir = validateNewOutputDirectory(outputDir, tmpRoot)
outputDir = string(outputDir);
if ~startsWith(outputDir, filesep)
    error("fig519:OutputMustBeAbsolute", "outputDir must be absolute.");
end
canonicalTmp = string(java.io.File(tmpRoot).getCanonicalPath());
canonicalOutput = string(java.io.File(outputDir).getCanonicalPath());
if ~startsWith(canonicalOutput, canonicalTmp + filesep) || ...
        canonicalOutput == canonicalTmp
    error("fig519:OutputOutsideTmp", ...
        "outputDir must be a new child below repository tmp/.");
end
if isfolder(outputDir) || isfile(outputDir)
    error("fig519:OutputAlreadyExists", "outputDir must not already exist.");
end
assertNoSymlinkAncestors(outputDir, canonicalTmp);
outputDir = canonicalOutput;
end

function runResult = loadFixedRawReference(pathValue, repo)
expectedRelative = fullfile("tmp", "fig519_initialization_20260831_A1", ...
    "raw_reference.mat");
expectedPath = string(java.io.File(fullfile(repo, expectedRelative)).getCanonicalPath());
pathValue = string(pathValue);
if ~startsWith(pathValue, filesep) || ~isfile(pathValue)
    error("fig519:RawReferenceMissing", ...
        "The existing raw reference must be an absolute regular file.");
end
assertNoSymlinkAncestors(pathValue, repo);
actualPath = string(java.io.File(pathValue).getCanonicalPath());
if actualPath ~= expectedPath || ...
        sha256File(actualPath) ~= ...
        "185d59ca6e55647ad14fb5f23599bc85e6566f8da2ca6120f42a0ef8dedbb648" || ...
        fileBytes(actualPath) ~= 299032
    error("fig519:RawReferenceContractMismatch", ...
        "The existing raw reference does not match the fixed Task 6 identity.");
end
loaded = load(actualPath, "runResult");
if ~isfield(loaded, "runResult") || ~isstruct(loaded.runResult)
    error("fig519:RawReferenceInvalid", ...
        "The fixed raw reference does not contain runResult.");
end
runResult = loaded.runResult;
end

function assertNoSymlinkAncestors(pathValue, stopAt)
probe = string(pathValue);
while strlength(probe) >= strlength(stopAt)
    javaPath = java.nio.file.Paths.get(char(probe), javaArray("java.lang.String", 0));
    if java.nio.file.Files.isSymbolicLink(javaPath)
        error("fig519:SymlinkPathForbidden", ...
            "Symlinked audit paths are forbidden: %s", probe);
    end
    if probe == stopAt
        return
    end
    parent = string(fileparts(probe));
    if parent == probe
        break
    end
    probe = parent;
end
error("fig519:OutputOutsideTmp", "Could not anchor outputDir below tmp/.");
end

function inventory = readInitialConditions(stateMeta)
inventory = repmat(struct("path", "", "value", NaN, ...
    "expression", ""), numel(stateMeta), 1);
for index = 1:numel(stateMeta)
    expression = string(get_param(stateMeta(index).path, "InitialCondition"));
    value = str2double(expression);
    if isnan(value)
        value = double(evalin("base", expression));
    end
    if ~isscalar(value) || ~isfinite(value) || ~isreal(value)
        error("fig519:InvalidInitialCondition", ...
            "State '%s' has a nonfinite or nonscalar initial condition.", ...
            stateMeta(index).path);
    end
    inventory(index).path = stateMeta(index).path;
    inventory(index).value = value;
    inventory(index).expression = expression;
end
end

function contract = auditSolverContract(model)
sampleTimes = Simulink.BlockDiagram.getSampleTimes(model);
records = repmat(struct("description", "", "value", [], ...
    "is_infinite", false, "infinite_positions", [], "semantic", ""), ...
    numel(sampleTimes), 1);
for index = 1:numel(sampleTimes)
    rawValue = double(sampleTimes(index).Value);
    records(index).description = string(sampleTimes(index).Description);
    records(index).value = rawValue(isfinite(rawValue));
    records(index).is_infinite = any(isinf(rawValue));
    records(index).infinite_positions = find(isinf(rawValue));
    if records(index).is_infinite && records(index).description == "Constant"
        records(index).semantic = "constant sample time (infinite period)";
    elseif isempty(rawValue)
        records(index).semantic = "multirate aggregate (no single numeric sample time)";
    else
        records(index).semantic = "finite compiled sample time";
    end
end
modelStopTime = string(get_param(model, "StopTime"));
contract = struct( ...
    "solver_name", string(get_param(model, "Solver")), ...
    "solver_type", string(get_param(model, "SolverType")), ...
    "fixed_step", string(get_param(model, "FixedStep")), ...
    "max_step", string(get_param(model, "MaxStep")), ...
    "model_stop_time_expression", modelStopTime, ...
    "reference_stop_time_s", 500, ...
    "stop_time_application", ...
        "Simulink.SimulationInput.setModelParameter (in-memory only)", ...
    "stop_time_dependency_checked", ...
        isfinite(str2double(modelStopTime)) && str2double(modelStopTime) == 14000, ...
    "compiled_sample_times", records);
end

function contract = auditBoundaryContract(model)
rootInports = find_system(model, "SearchDepth", 1, "BlockType", "Inport");
rootBlocks = find_system(model, "SearchDepth", 1, "Type", "Block");
rootSources = strings(0, 1);
for index = 1:numel(rootBlocks)
    handles = get_param(rootBlocks{index}, "PortHandles");
    hasInputs = ~isempty(handles.Inport) || ~isempty(handles.Enable) || ...
        ~isempty(handles.Trigger) || ~isempty(handles.Ifaction) || ...
        ~isempty(handles.Reset);
    if ~hasInputs && ~isempty(handles.Outport)
        rootSources(end + 1, 1) = string(rootBlocks{index}); %#ok<AGROW>
    end
end
sources = repmat(struct("path", "", "block_type", "", ...
    "classification", "", "value_expression", "", ...
    "destination_connections", emptyGraphHop()), numel(rootSources), 1);
for index = 1:numel(rootSources)
    sources(index).path = rootSources(index);
    sources(index).block_type = string(get_param(rootSources(index), "BlockType"));
    sources(index).classification = "fixed_internal_boundary_source";
    if sources(index).block_type == "Constant"
        sources(index).value_expression = string(get_param(rootSources(index), "Value"));
    end
    sources(index).destination_connections = ...
        outgoingSignalHops(rootSources(index));
end
contract = struct( ...
    "root_inport_count", numel(rootInports), ...
    "root_inports", string(rootInports(:)), ...
    "root_source_blocks", sources, ...
    "classification_note", ...
        "No external root Inports exist; every root block with outputs and no input ports is enumerated with its official-API destination connections.", ...
    "all_inputs_classified", isempty(rootInports) && ~isempty(rootSources) && ...
        all(string({sources.classification}) == "fixed_internal_boundary_source"));
end

function paths = auditPowerPaths(model, manifest)
blocks = find_system(model, "FollowLinks", "on", ...
    "LookUnderMasks", "all", "BlockType", "ToWorkspace");
variables = strings(numel(blocks), 1);
for index = 1:numel(blocks)
    variables(index) = string(get_param(blocks{index}, "VariableName"));
end
pBlock = blocks(variables == "P_sw");
if numel(pBlock) ~= 1
    error("fig519:PswTraceMismatch", ...
        "Expected exactly one P_sw To Workspace block, found %d.", numel(pBlock));
end
[pSource, pPort] = upstreamSource(pBlock{1});

turbine = manifest(string({manifest.name}) == "turbine_power");
compressor = manifest(string({manifest.name}) == "compressor_power");
if numel(turbine) ~= 1 || numel(compressor) ~= 1 || ...
        turbine.port ~= 4 || compressor.port ~= 2
    error("fig519:PowerManifestMismatch", ...
        "Turbine output 4 or compressor output 2 is missing from the manifest.");
end

loadSource = model + "/Constant14";
loadDestination = model + "/TAC";
loadInport = loadDestination + "/Pload";
loadExpression = string(get_param(loadSource, "Value"));
loadValue = str2double(loadExpression);
if isnan(loadValue)
    loadValue = double(evalin("base", loadExpression));
end
connectivity = get_param(loadSource, "PortConnectivity");
destinationBlocks = strings(0, 1);
destinationPorts = zeros(0, 1);
for connectionIndex = 1:numel(connectivity)
    if ~isempty(connectivity(connectionIndex).DstBlock)
        handles = connectivity(connectionIndex).DstBlock(:);
        ports = connectivity(connectionIndex).DstPort(:);
        for destinationIndex = 1:numel(handles)
            destinationBlocks(end + 1, 1) = ...
                string(getfullname(handles(destinationIndex))); %#ok<AGROW>
            destinationPorts(end + 1, 1) = ...
                double(ports(destinationIndex)) + 1; %#ok<AGROW>
        end
    end
end
loadMatches = destinationBlocks == loadDestination & destinationPorts == 6;
if nnz(loadMatches) ~= 1 || string(get_param(loadInport, "BlockType")) ~= "Inport" || ...
        str2double(get_param(loadInport, "Port")) ~= 6 || ...
        ~isscalar(loadValue) || ~isfinite(loadValue) || loadValue ~= 1000.21e3
    error("fig519:LoadTraceMismatch", ...
        "Constant14 must directly feed TAC input 6/Pload with 1000.21e3 W.");
end

outports = find_system(model + "/TAC", "FollowLinks", "on", ...
    "LookUnderMasks", "all", "BlockType", "Outport");
searched = strings(0, 1);
matches = strings(0, 1);
for index = 1:numel(blocks)
    searched(end + 1, 1) = string(blocks{index}) + ...
        " [VariableName=" + variables(index) + "]"; %#ok<AGROW>
    if isGeneratorIdentity(string(blocks{index}) + " " + variables(index))
        matches(end + 1, 1) = searched(end); %#ok<AGROW>
    end
end
for index = 1:numel(outports)
    identity = string(outports{index}) + " [Name=" + ...
        string(get_param(outports{index}, "Name")) + "]";
    searched(end + 1, 1) = identity; %#ok<AGROW>
    if isGeneratorIdentity(identity)
        matches(end + 1, 1) = identity; %#ok<AGROW>
    end
end

paths = struct( ...
    "reactor", struct( ...
        "status", "verified_by_official_api", ...
        "workspace_block", string(pBlock{1}), ...
        "workspace_variable", "P_sw", ...
        "upstream_block", pSource, ...
        "upstream_output_port", pPort), ...
    "turbine", struct( ...
        "status", "verified_by_official_api", ...
        "block", turbine.block, "output_port", turbine.port, ...
        "manifest_name", turbine.name), ...
    "compressor", struct( ...
        "status", "verified_by_official_api", ...
        "block", compressor.block, "output_port", compressor.port, ...
        "manifest_name", compressor.name), ...
    "load", struct( ...
        "status", "verified_by_official_api", ...
        "source_block", loadSource, ...
        "source_output_port", 1, ...
        "value_expression", loadExpression, ...
        "value_W", loadValue, ...
        "destination_block", loadDestination, ...
        "destination_input_port", 6, ...
        "destination_inport_block", loadInport, ...
        "destination_inport_name", string(get_param(loadInport, "Name"))), ...
    "electrical", struct( ...
        "status", "no_direct_generator_signal_found", ...
        "search_terms", ["generator", "electrical", "electric", ...
            "p_e", "wgen", "pgen", "pelec"], ...
        "searched_to_workspace_and_tac_outports", searched, ...
        "matching_direct_signals", matches), ...
    "direct_generator_signal_found", ~isempty(matches));
end

function yes = isGeneratorIdentity(identity)
identity = lower(string(identity));
terms = ["generator", "electrical", "electric", "p_e", "wgen", ...
    "pgen", "pelec"];
yes = any(contains(identity, terms));
end

function [source, sourcePort] = upstreamSource(block)
connectivity = get_param(block, "PortConnectivity");
source = "";
sourcePort = NaN;
for index = 1:numel(connectivity)
    if ~isempty(connectivity(index).SrcBlock)
        source = string(getfullname(connectivity(index).SrcBlock));
        sourcePort = double(connectivity(index).SrcPort) + 1;
        break
    end
end
if source == "" || ~isfinite(sourcePort)
    error("fig519:MissingUpstreamSource", ...
        "Could not trace an upstream source for '%s'.", block);
end
end

function contract = auditPowerStatePaths(model, powerPaths)
edges = officialApiBlockGraph(model);
reactorCandidates = [model + "/reactor/Integrator6"; ...
    model + "/reactor/Integrator7"];
turbineCandidates = [ ...
    model + "/IHX/IHX_region_2/T_c1_average_Integrator"; ...
    model + "/IHX/IHX_region_2/T_c2_out_Integrator"; ...
    model + "/TAC/rotor/N_rpm_Integrator"];
compressorCandidates = [ ...
    model + "/precooler/precooler_2/T_h1_average_Integrator"; ...
    model + "/precooler/precooler_2/T_h2_out_Integrator"; ...
    model + "/TAC/rotor/N_rpm_Integrator"];
contract = struct( ...
    "graph_builder", "Simulink official PortHandles/Line/DstPortHandle API", ...
    "reactor", traceCandidates(edges, reactorCandidates, ...
        string(powerPaths.reactor.workspace_block), 1, "input", ...
        "reactor_power_logger"), ...
    "turbine", traceCandidates(edges, turbineCandidates, ...
        string(powerPaths.turbine.block), powerPaths.turbine.output_port, ...
        "output", "turbine_power_output"), ...
    "compressor", traceCandidates(edges, compressorCandidates, ...
        string(powerPaths.compressor.block), powerPaths.compressor.output_port, ...
        "output", "compressor_power_output"));
if isempty(contract.reactor) || isempty(contract.turbine) || ...
        isempty(contract.compressor)
    error("fig519:PowerStateApiTraceMissing", ...
        "Official-API state paths found: reactor=%d turbine=%d compressor=%d.", ...
        numel(contract.reactor), numel(contract.turbine), ...
        numel(contract.compressor));
end
end

function records = traceCandidates( ...
        edges, candidates, endpoint, endpointPort, endpointPortKind, endpointRole)
records = emptyTraceRecord();
for index = 1:numel(candidates)
    hops = shortestGraphPath(edges, candidates(index), endpoint, ...
        endpointPort, endpointPortKind);
    if isempty(hops)
        continue
    end
    record = struct( ...
        "state_path", candidates(index), ...
        "endpoint_block", endpoint, ...
        "endpoint_port", double(endpointPort), ...
        "endpoint_port_kind", string(endpointPortKind), ...
        "endpoint_role", string(endpointRole), ...
        "status", "verified_by_official_api_graph", ...
        "hops", hops);
    records(end + 1, 1) = record; %#ok<AGROW>
end
end

function edges = officialApiBlockGraph(model)
blocks = string(find_system(model, "FollowLinks", "on", ...
    "LookUnderMasks", "all", "Type", "Block"));
edges = emptyGraphHop();
for index = 1:numel(blocks)
    edges = [edges; outgoingSignalHops(blocks(index))]; %#ok<AGROW>
    blockType = string(get_param(blocks(index), "BlockType"));
    if blockType ~= "SubSystem"
        if blockType == "From"
            goto = get_param(blocks(index), "GotoBlock");
            if isstruct(goto) && isfield(goto, "name") && string(goto.name) ~= ""
                edges(end + 1, 1) = graphHop(string(goto.name), 1, "input", ...
                    blocks(index), 1, "output", "goto_from"); %#ok<AGROW>
            end
        elseif ~ismember(blockType, ["Inport", "Outport", "Goto"])
            edges = [edges; blockDependencyHops(blocks(index))]; %#ok<AGROW>
        end
        continue
    end
    inports = string(find_system(blocks(index), "FollowLinks", "on", ...
        "LookUnderMasks", "all", "SearchDepth", 1, "BlockType", "Inport"));
    for inportIndex = 1:numel(inports)
        port = str2double(get_param(inports(inportIndex), "Port"));
        edges(end + 1, 1) = graphHop(blocks(index), port, "input", ...
            inports(inportIndex), 1, "output", "subsystem_inport"); %#ok<AGROW>
    end
    outports = string(find_system(blocks(index), "FollowLinks", "on", ...
        "LookUnderMasks", "all", "SearchDepth", 1, "BlockType", "Outport"));
    for outportIndex = 1:numel(outports)
        port = str2double(get_param(outports(outportIndex), "Port"));
        edges(end + 1, 1) = graphHop(outports(outportIndex), 1, "input", ...
            blocks(index), port, "output", "subsystem_outport"); %#ok<AGROW>
    end
end
end

function hops = blockDependencyHops(block)
hops = emptyGraphHop();
handles = get_param(block, "PortHandles");
for inputIndex = 1:numel(handles.Inport)
    inputPort = double(get_param(handles.Inport(inputIndex), "PortNumber"));
    for outputIndex = 1:numel(handles.Outport)
        outputPort = double(get_param(handles.Outport(outputIndex), "PortNumber"));
        hops(end + 1, 1) = graphHop(block, inputPort, "input", ...
            block, outputPort, "output", "block_dependency"); %#ok<AGROW>
    end
end
end

function hops = outgoingSignalHops(block)
hops = emptyGraphHop();
handles = get_param(block, "PortHandles");
for outputIndex = 1:numel(handles.Outport)
    line = get_param(handles.Outport(outputIndex), "Line");
    if isempty(line) || line == -1
        continue
    end
    destinations = get_param(line, "DstPortHandle");
    destinations = destinations(destinations ~= -1);
    for destinationIndex = 1:numel(destinations)
        destination = destinations(destinationIndex);
        outputPort = double(get_param(handles.Outport(outputIndex), "PortNumber"));
        hops(end + 1, 1) = graphHop(block, outputPort, "output", ...
            string(get_param(destination, "Parent")), ...
            double(get_param(destination, "PortNumber")), "input", ...
            "signal_line"); %#ok<AGROW>
    end
end
end

function hops = shortestGraphPath(edges, source, target, targetPort, targetPortKind)
hops = emptyGraphHop();
source = string(source);
target = string(target);
sourceKey = terminalKey(source, "output", 1);
targetKey = terminalKey(target, targetPortKind, targetPort);
queue = sourceKey;
head = 1;
visited = containers.Map("KeyType", "char", "ValueType", "logical");
visited(char(sourceKey)) = true;
predecessor = containers.Map("KeyType", "char", "ValueType", "double");
fromKeys = arrayfun(@(edge) terminalKey(edge.from_block, ...
    edge.from_port_kind, edge.from_port), edges, "UniformOutput", false);
while head <= numel(queue)
    current = queue(head);
    head = head + 1;
    candidates = find(string(fromKeys) == current);
    for candidateIndex = 1:numel(candidates)
        index = candidates(candidateIndex);
        nextKey = terminalKey(edges(index).to_block, ...
            edges(index).to_port_kind, edges(index).to_port);
        if isKey(visited, char(nextKey))
            continue
        end
        visited(char(nextKey)) = true;
        predecessor(char(nextKey)) = index;
        queue(end + 1, 1) = nextKey; %#ok<AGROW>
        if nextKey == targetKey
            cursor = nextKey;
            while cursor ~= sourceKey
                edgeIndex = predecessor(char(cursor));
                hops = [edges(edgeIndex); hops]; %#ok<AGROW>
                cursor = terminalKey(edges(edgeIndex).from_block, ...
                    edges(edgeIndex).from_port_kind, edges(edgeIndex).from_port);
            end
            return
        end
    end
end
end

function key = terminalKey(block, kind, port)
key = string(block) + "\x1f" + string(kind) + "\x1f" + string(port);
end

function item = graphHop(fromBlock, fromPort, fromKind, ...
        toBlock, toPort, toKind, bridgeKind)
item = struct( ...
    "from_block", string(fromBlock), ...
    "from_port", double(fromPort), ...
    "from_port_kind", string(fromKind), ...
    "to_block", string(toBlock), ...
    "to_port", double(toPort), ...
    "to_port_kind", string(toKind), ...
    "bridge_kind", string(bridgeKind));
end

function items = emptyGraphHop()
items = repmat(graphHop("", NaN, "", "", NaN, "", ""), 0, 1);
end

function items = emptyTraceRecord()
items = repmat(struct("state_path", "", "endpoint_block", "", ...
    "endpoint_port", NaN, "endpoint_port_kind", "", ...
    "endpoint_role", "", "status", "", "hops", emptyGraphHop()), 0, 1);
end

function records = residualContracts(model, powerPaths)
blankPaths = strings(0, 1);
records = repmat(struct("name", "", "status", "not_observable", ...
    "value", NaN, "unit", "", "formula", "", ...
    "source_paths", blankPaths, "missing_direct_signals", blankPaths), 6, 1);
records(1) = residual("reactor_power_derivative", "computed", "W/s", ...
    "(P_state(t1)-P_state(t0))/(t1-t0)", ...
    string(powerPaths.reactor.upstream_block), strings(0, 1));
records(2) = residual("shaft_excess_power", "computed", "W", ...
    "WT(t0)-Wc(t0)-Pload", ...
    [string(powerPaths.turbine.block); string(powerPaths.compressor.block); ...
     string(powerPaths.load.source_block); ...
     string(powerPaths.load.destination_inport_block)], strings(0, 1));
records(3) = residual("ihx_energy", "not_observable", "W", ...
    "Q_hot_in-Q_hot_out-(Q_cold_out-Q_cold_in)-dU_wall/dt", ...
    model + "/IHX", ["IHX direct hot-side enthalpy-flow inlet/outlet"; ...
    "IHX direct cold-side enthalpy-flow inlet/outlet"; "IHX wall-energy derivative"]);
records(4) = residual("recuperator_energy", "not_observable", "W", ...
    "Q_hot_in-Q_hot_out-(Q_cold_out-Q_cold_in)-dU_wall/dt", ...
    model + "/recuperator", ["recuperator direct hot-side enthalpy-flow inlet/outlet"; ...
    "recuperator direct cold-side enthalpy-flow inlet/outlet"; "recuperator wall-energy derivative"]);
records(5) = residual("precooler_energy", "not_observable", "W", ...
    "Q_hot_in-Q_hot_out-Q_coolant-dU_wall/dt", ...
    model + "/precooler", ["precooler direct He-Xe enthalpy-flow inlet/outlet"; ...
    "precooler direct coolant heat-flow inlet/outlet"; "precooler wall-energy derivative"]);
records(6) = residual("radiator_energy", "not_observable", "W", ...
    "Q_coolant_in-Q_coolant_out-Q_radiated-dU_radiator/dt", ...
    model + "/rediator", ["rediator direct coolant enthalpy-flow inlet/outlet"; ...
    "rediator direct radiative heat rejection"; "rediator stored-energy derivative"]);
end

function item = residual(name, status, unit, formula, sourcePaths, missing)
item = struct("name", string(name), "status", string(status), ...
    "value", NaN, "unit", string(unit), "formula", string(formula), ...
    "source_paths", string(sourcePaths(:)), ...
    "missing_direct_signals", string(missing(:)));
end

function inventory = buildStateInventory(stateMeta, initial, runResult)
inventory = repmat(struct( ...
    "path", "", "fluid", "", "kind", "", "sign_policy", "", ...
    "initial_condition_expression", "", "initial_condition", NaN, ...
    "t0_value", NaN, "t500_value", NaN, "absolute_change", NaN, ...
    "relative_change", NaN, "relative_change_defined", false, ...
    "first_sample_slope", NaN, "first_sample_slope_unit", "state_unit/s"), ...
    numel(stateMeta), 1);
for index = 1:numel(stateMeta)
    if ~isfield(runResult.states(index), "path") || ...
            string(runResult.states(index).path) ~= string(stateMeta(index).path)
        error("fig519:RawStateOrderMismatch", ...
            "Fixed raw state %d does not match the official manifest path.", index);
    end
    data = double(runResult.states(index).data(:));
    delta = data(end) - data(1);
    relativeDefined = data(1) ~= 0;
    relative = NaN;
    if relativeDefined
        relative = delta / data(1);
    end
    inventory(index).path = stateMeta(index).path;
    inventory(index).fluid = stateMeta(index).fluid;
    inventory(index).kind = stateMeta(index).kind;
    inventory(index).sign_policy = stateMeta(index).signPolicy;
    inventory(index).initial_condition_expression = initial(index).expression;
    inventory(index).initial_condition = initial(index).value;
    inventory(index).t0_value = data(1);
    inventory(index).t500_value = data(end);
    inventory(index).absolute_change = delta;
    inventory(index).relative_change = relative;
    inventory(index).relative_change_defined = relativeDefined;
    inventory(index).first_sample_slope = ...
        (data(2) - data(1)) / (runResult.t(2) - runResult.t(1));
end
end

function result = calculateResiduals(templates, inventory, runResult, powerPaths)
items = templates;
powerIndex = find(string({inventory.path}) == ...
    "final_steady_24a/reactor/Integrator6", 1);
items(1).value = inventory(powerIndex).first_sample_slope;
items(2).value = double(runResult.signals.turbine_power(1)) - ...
    double(runResult.signals.compressor_power(1)) - powerPaths.load.value_W;
result = struct("items", items, ...
    "all_items_accounted_for", all(arrayfun(@(item) ...
        string(item.status) == "computed" || ...
        (string(item.status) == "not_observable" && ...
         ~isempty(item.missing_direct_signals)), items)), ...
    "reference_first_interval_s", [runResult.t(1), runResult.t(2)], ...
    "fitted_values_used", false);
end

function explanation = explainFlatStart( ...
        inventory, runResult, powerPaths, traceContract)
t = double(runResult.t(:));
signals = runResult.signals;
reactor = double(signals.reactor_power(:));
turbine = double(signals.turbine_power(:));
compressor = double(signals.compressor_power(:));
electrical = 0.98 .* (turbine - compressor);
definitions = [ ...
    powerEvidence("reactor", "P_sw", powerPaths.reactor.upstream_block, t, reactor); ...
    powerEvidence("turbine", "WT_sw", powerPaths.turbine.block, t, turbine); ...
    powerEvidence("compressor", "Wc_sw", powerPaths.compressor.block, t, compressor); ...
    powerEvidence("electrical_paper_eta", "0.98*(WT_sw-Wc_sw)", ...
        "offline derivation from verified turbine/compressor paths", t, electrical)];
threshold = 1e-6;
stateEvidence = repmat(struct("path", "", "first_sample_slope", NaN, ...
    "normalized_first_sample_slope_per_s", NaN, ...
    "near_zero_by_rule", false, "absolute_change_500s", NaN), ...
    numel(inventory), 1);
for index = 1:numel(inventory)
    stateEvidence(index).path = inventory(index).path;
    stateEvidence(index).first_sample_slope = inventory(index).first_sample_slope;
    stateEvidence(index).normalized_first_sample_slope_per_s = ...
        abs(inventory(index).first_sample_slope) / ...
        max(abs(inventory(index).t0_value), 1);
    stateEvidence(index).near_zero_by_rule = ...
        stateEvidence(index).normalized_first_sample_slope_per_s <= threshold;
    stateEvidence(index).absolute_change_500s = inventory(index).absolute_change;
end
nearZero = stateEvidence([stateEvidence.near_zero_by_rule]);
model = "final_steady_24a";
reactorStates = string({traceContract.reactor.state_path})';
turbineStates = string({traceContract.turbine.state_path})';
compressorStates = string({traceContract.compressor.state_path})';
electricalStates = unique([turbineStates; compressorStates], "stable");
mappings = [ ...
    powerMapping("reactor", reactorStates, ...
        [string(powerPaths.reactor.upstream_block); ...
         string(powerPaths.reactor.workspace_block)], ...
        "Only recorded reactor states with an official-API graph path to the P_sw logger are listed.", ...
        "verified_by_official_api_graph", traceContract.reactor, true, strings(0, 1)); ...
    powerMapping("turbine", turbineStates, ...
        [string(powerPaths.turbine.block) + " output 4"; ...
         model + "/TAC/WT_sw"], ...
        "Only recorded states with an official-API graph path to the Turbine component are listed.", ...
        "verified_by_official_api_graph", traceContract.turbine, true, strings(0, 1)); ...
    powerMapping("compressor", compressorStates, ...
        [string(powerPaths.compressor.block) + " output 2"; ...
         model + "/TAC/Wc_sw"], ...
        "Only recorded states with an official-API graph path to the Compressor component are listed.", ...
        "verified_by_official_api_graph", traceContract.compressor, true, strings(0, 1)); ...
    powerMapping("electrical_paper_eta", electricalStates, ...
        [string(powerPaths.turbine.block) + " output 4"; model + "/TAC/WT_sw"; ...
         string(powerPaths.compressor.block) + " output 2"; model + "/TAC/Wc_sw"], ...
        "The electrical definition is only an offline composition of the two API-verified shaft paths; no direct model endpoint is claimed.", ...
        "verified_offline_composition_of_api_traces", emptyTraceRecord(), false, ...
        ["turbine"; "compressor"])];
nearZeroPaths = string({nearZero.path});
mappingStateComplete = numel(mappings) == 4 && all(arrayfun(@(item) ...
    ~isempty(item.traced_state_paths) && ...
    all(ismember(string(item.traced_state_paths), nearZeroPaths)), mappings));
mappingSignalComplete = all(arrayfun(@(item) ...
    mappingApiEvidenceComplete(item), mappings));
explanation = struct( ...
    "conclusion", ...
        "The unmodified 500 s run directly supplies state slopes and verified signal-path power traces; it does not identify the authors' initial-state vector.", ...
    "near_zero_rule", struct( ...
        "metric", "abs(first_sample_slope)/max(abs(t0_value),1)", ...
        "threshold_per_s", threshold, ...
        "classification", ...
            "numerical diagnostic only; does not alter physical equations"), ...
    "near_zero_state_derivatives", nearZero, ...
    "power_state_signal_mappings", mappings, ...
    "has_state_evidence", numel(stateEvidence) == 40 && ...
        ~isempty(nearZero) && mappingStateComplete, ...
    "has_signal_path_evidence", mappingSignalComplete, ...
    "state_derivative_evidence", stateEvidence, ...
    "power_definitions", definitions, ...
    "paper_initial_state_identified", false, ...
    "fitted_values_used", false);
end

function item = powerMapping(name, statePaths, signalPaths, explanation, ...
        verificationStatus, traceRecords, directEndpointClaimed, compositionSources)
item = struct("power_definition", string(name), ...
    "traced_state_paths", string(statePaths(:)), ...
    "traced_signal_paths", string(signalPaths(:)), ...
    "mapping_explanation", string(explanation), ...
    "api_verification_status", string(verificationStatus), ...
    "api_trace_records", traceRecords, ...
    "direct_model_endpoint_claimed", logical(directEndpointClaimed), ...
    "composition_sources", string(compositionSources(:)));
end

function yes = mappingApiEvidenceComplete(mapping)
if any(strlength(string(mapping.traced_signal_paths)) == 0)
    yes = false;
    return
end
if string(mapping.power_definition) == "electrical_paper_eta"
    yes = string(mapping.api_verification_status) == ...
        "verified_offline_composition_of_api_traces" && ...
        ~mapping.direct_model_endpoint_claimed && ...
        isempty(mapping.api_trace_records) && ...
        isequal(sort(string(mapping.composition_sources)), ...
            sort(["turbine"; "compressor"]));
    return
end
records = mapping.api_trace_records;
yes = string(mapping.api_verification_status) == ...
    "verified_by_official_api_graph" && mapping.direct_model_endpoint_claimed && ...
    numel(records) == numel(mapping.traced_state_paths) && ~isempty(records);
for index = 1:numel(records)
    hops = records(index).hops;
    yes = yes && string(records(index).status) == ...
        "verified_by_official_api_graph" && ~isempty(hops) && ...
        string(hops(1).from_block) == string(records(index).state_path) && ...
        string(hops(end).to_block) == string(records(index).endpoint_block) && ...
        hops(end).to_port == records(index).endpoint_port && ...
        string(hops(end).to_port_kind) == ...
            string(records(index).endpoint_port_kind) && ...
        all(ismember(string({hops.bridge_kind}), ...
            ["signal_line", "subsystem_inport", "subsystem_outport", ...
             "goto_from", "block_dependency"]));
end
end

function item = powerEvidence(name, definition, pathValue, t, values)
item = struct( ...
    "name", string(name), ...
    "definition", string(definition), ...
    "source_path", string(pathValue), ...
    "first_sample_slope_W_per_s", (values(2)-values(1))/(t(2)-t(1)), ...
    "peak_to_peak_0_to_500_W", max(values)-min(values), ...
    "start_W", values(1), "end_W", values(end));
end

function summary = verifyProtectedManifest(manifestPath)
tableData = readtable(manifestPath, TextType="string");
required = ["resolved_path", "resolved_sha256"];
if height(tableData) ~= 34 || ~all(ismember(required, string(tableData.Properties.VariableNames)))
    error("fig519:ProtectedManifestInvalid", ...
        "Protected recovery manifest must contain 34 resolved rows.");
end
for index = 1:height(tableData)
    pathValue = tableData.resolved_path(index);
    if ~isfile(pathValue) || sha256File(pathValue) ~= tableData.resolved_sha256(index)
        error("fig519:ProtectedManifestMismatch", ...
            "Protected entry failed resolution: %s", pathValue);
    end
end
summary = struct("row_count", height(tableData), ...
    "resolved_count", height(tableData), "unresolved_count", 0, ...
    "manifest_path", string(manifestPath), ...
    "manifest_sha256", sha256File(manifestPath));
end

function count = fileBytes(pathValue)
info = dir(pathValue);
count = info.bytes;
end

function relative = relativeToRepo(pathValue, repo)
prefix = repo + filesep;
pathValue = string(pathValue);
if ~startsWith(pathValue, prefix)
    error("fig519:PathOutsideRepository", ...
        "Expected an audit artifact below the repository root.");
end
relative = extractAfter(pathValue, strlength(prefix));
end

function writeExclusiveText(pathValue, payload)
if isfile(pathValue) || isfolder(pathValue)
    error("fig519:OutputConflict", "Refusing to replace an audit artifact.");
end
% outputDir was created as a new, private audit directory by this function;
% MATLAB fopen has no POSIX O_EXCL mode, so the explicit nonexistence check
% above is the ownership gate for this exploration artifact.
file = fopen(pathValue, "w");
if file < 0
    error("fig519:OutputWriteFailed", "Could not create '%s'.", pathValue);
end
cleanup = onCleanup(@() fclose(file));
count = fwrite(file, char(payload), "char");
if count ~= strlength(payload)
    error("fig519:OutputWriteFailed", "Short write for '%s'.", pathValue);
end
end

function closeWithoutSaving(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end

function names = startWorkspaceVariables(startPath)
variablesBefore = string(who);
run(startPath);
variablesAfter = string(who);
helperVariables = [variablesBefore; "variablesBefore"; ...
    "variablesAfter"; "helperVariables"; "names"];
names = setdiff(variablesAfter, helperVariables, "stable");
end

function snapshot = captureBaseWorkspace(names)
names = string(names(:));
snapshot = struct("names", names, "existed", false(size(names)), ...
    "values", {cell(size(names))});
for index = 1:numel(names)
    snapshot.existed(index) = evalin("base", ...
        "exist(" + matlabString(names(index)) + ", 'var') == 1");
    if snapshot.existed(index)
        snapshot.values{index} = evalin("base", names(index));
    end
end
end

function restoreBaseWorkspace(snapshot)
for index = 1:numel(snapshot.names)
    name = snapshot.names(index);
    if snapshot.existed(index)
        assignin("base", name, snapshot.values{index});
    else
        evalin("base", "clear " + name);
    end
end
end

function hash = sha256File(filePath)
[status, output] = system("shasum -a 256 " + shellQuote(filePath));
if status ~= 0
    error("fig519:HashFailed", "Could not hash '%s': %s", filePath, output);
end
parts = split(strtrim(output));
hash = string(parts(1));
end

function quoted = shellQuote(value)
quoted = "'" + replace(string(value), "'", "'\\''") + "'";
end

function quoted = matlabString(value)
quoted = "'" + replace(string(value), "'", "''") + "'";
end
