function out = audit_rotating_map_candidates(repoRoot, outputDir, candidatePath)
%AUDIT_ROTATING_MAP_CANDIDATES Offline-only Gate 1 map comparison.
%   This function reads MAT arrays, evaluates fixed design anchors and curve
%   shape/domain gates, and writes JSON/CSV/PNG evidence.  It never loads or
%   simulates a Simulink model and never changes any source MAT file.

arguments
    repoRoot (1,1) string
    outputDir (1,1) string
    candidatePath (1,1) string = fullfile(repoRoot, "data", ...
        "provenance", "rotating_machinery", "recovered_20260902", ...
        "source", "Xu2022_PaperStyle_Equivalent_Lookup.mat")
end

repoRoot = canonicalPath(repoRoot, true);
outputDir = canonicalPath(outputDir, false);
candidatePath = canonicalPath(candidatePath, true);
if isfolder(outputDir) || isfile(outputDir)
    error("rotatingMap:OutputExists", ...
        "Offline-audit output already exists: %s", outputDir);
end

compressorPath = fullfile(repoRoot, "hexe_compressor_lookup.mat");
turbineFlowPath = fullfile(repoRoot, "turbine_table1.mat");
turbineEfficiencyPath = fullfile(repoRoot, "turbine_table2.mat");
currentCompressor = load(compressorPath);
currentTurbineFlow = load(turbineFlowPath);
currentTurbineEfficiency = load(turbineEfficiencyPath);
candidate = load(candidatePath);

validateCurrent(currentCompressor, currentTurbineFlow, ...
    currentTurbineEfficiency);
validateCandidate(candidate);

target = designTargets();
requiredSpeeds = [22036, 50610, 55090, 57844.5, 59655];
current = evaluateCurrent(currentCompressor, currentTurbineFlow, ...
    currentTurbineEfficiency, target, requiredSpeeds);
recovered = evaluateCandidate(candidate, target, requiredSpeeds);

out = struct;
out.schema = "rotating_map_offline_audit_v1";
out.analysis_kind = "offline_mat_only";
out.simulation_call_count = 0;
out.source_files = struct( ...
    "current_compressor", sourceIdentity(compressorPath, repoRoot), ...
    "current_turbine_flow", sourceIdentity(turbineFlowPath, repoRoot), ...
    "current_turbine_efficiency", ...
        sourceIdentity(turbineEfficiencyPath, repoRoot), ...
    "candidate", sourceIdentity(candidatePath, repoRoot));
out.targets = target;
out.required_speeds_rpm = requiredSpeeds;
out.current = current;
out.candidate = recovered;
out.evidence = struct( ...
    "current_compressor_origin", ...
        "NASA TM X-2269 argon-derived transformed candidate", ...
    "current_turbine_origin", "binary arrays with no closed builder chain", ...
    "candidate_origin", ...
        "Xu Table 5.2 anchors plus Gallo 2007 shape reconstruction", ...
    "candidate_limitation", ...
        "100%-110% speed region is explicit linear extrapolation", ...
    "author_original_status", "not_recovered");
out.paper_reproduced = false;
out.author_original_lookup_recovered = false;
out.formal_promotion = false;

mkdir(outputDir);
try
    writeOutputs(out, current, recovered, candidate, currentCompressor, ...
        currentTurbineFlow, currentTurbineEfficiency, outputDir);
catch exception
    if isfolder(outputDir)
        rmdir(outputDir, "s");
    end
    rethrow(exception)
end
end

function validateCurrent(compressor, turbineFlow, turbineEfficiency)
requireFields(compressor, ["speed_bp", "m_ratio_bp", "PR_table", ...
    "ETAT_table", "N_design", "mdot_design"], "current compressor");
requireFields(turbineFlow, ["bp_er", "bp_speed", "table_mf"], ...
    "current turbine flow");
requireFields(turbineEfficiency, ["bp_mf", "bp_speed", "table_eff"], ...
    "current turbine efficiency");
if ~isequal(size(compressor.PR_table), ...
        [numel(compressor.speed_bp), numel(compressor.m_ratio_bp)]) || ...
        ~isequal(size(compressor.ETAT_table), size(compressor.PR_table)) || ...
        ~isequal(size(turbineFlow.table_mf), ...
        [numel(turbineFlow.bp_er), numel(turbineFlow.bp_speed)]) || ...
        ~isequal(size(turbineEfficiency.table_eff), ...
        [numel(turbineEfficiency.bp_mf), ...
        numel(turbineEfficiency.bp_speed)])
    error("rotatingMap:InvalidCurrent", ...
        "Current lookup dimensions do not match their breakpoints.");
end
assertFiniteNumeric([compressor.speed_bp(:); compressor.m_ratio_bp(:); ...
    compressor.PR_table(:); compressor.ETAT_table(:); ...
    turbineFlow.bp_er(:); turbineFlow.bp_speed(:); ...
    turbineFlow.table_mf(:); turbineEfficiency.bp_mf(:); ...
    turbineEfficiency.bp_speed(:); turbineEfficiency.table_eff(:)], ...
    "rotatingMap:InvalidCurrent", "current lookup");
end

function validateCandidate(candidate)
required = ["N_bp", "mC_bp", "PRc_tbl", "etac_tbl", "PRt_bp", ...
    "mT_tbl", "mT_bp", "etat_tbl", "metadata"];
requireFields(candidate, required, "candidate", ...
    "rotatingMap:InvalidCandidate");
dimensionsAreValid = ...
    isequal(size(candidate.PRc_tbl), ...
        [numel(candidate.N_bp), numel(candidate.mC_bp)]) && ...
    isequal(size(candidate.etac_tbl), size(candidate.PRc_tbl)) && ...
    isequal(size(candidate.mT_tbl), ...
        [numel(candidate.N_bp), numel(candidate.PRt_bp)]) && ...
    isequal(size(candidate.etat_tbl), ...
        [numel(candidate.N_bp), numel(candidate.mT_bp)]);
if ~dimensionsAreValid
    error("rotatingMap:InvalidCandidate", ...
        "Candidate lookup dimensions do not match the declared axes.");
end
numeric = [candidate.N_bp(:); candidate.mC_bp(:); ...
    candidate.PRc_tbl(:); candidate.etac_tbl(:); ...
    candidate.PRt_bp(:); candidate.mT_tbl(:); candidate.mT_bp(:); ...
    candidate.etat_tbl(:)];
assertFiniteNumeric(numeric, "rotatingMap:InvalidCandidate", "candidate");
if any(diff(candidate.N_bp(:)) <= 0) || ...
        any(diff(candidate.mC_bp(:)) <= 0) || ...
        any(diff(candidate.PRt_bp(:)) <= 0) || ...
        any(diff(candidate.mT_bp(:)) <= 0)
    error("rotatingMap:InvalidCandidate", ...
        "Candidate axes must be strictly increasing.");
end
if any(candidate.PRc_tbl(:) <= 1) || ...
        any(candidate.etac_tbl(:) < 0 | candidate.etac_tbl(:) > 1) || ...
        any(candidate.mT_tbl(:) <= 0) || ...
        any(candidate.etat_tbl(:) < 0 | candidate.etat_tbl(:) > 1)
    error("rotatingMap:InvalidCandidate", ...
        "Candidate pressure, flow, or efficiency range is invalid.");
end
end

function value = designTargets()
value = struct( ...
    "speed_rpm", 55090, ...
    "compressor_mass_flow_kg_s", 12.022308, ...
    "compressor_pressure_ratio", 1.551 / 0.658, ...
    "compressor_efficiency", 0.842737535, ...
    "turbine_pressure_ratio", 1.539 / 0.676, ...
    "turbine_mass_flow_kg_s", 12.022308, ...
    "turbine_efficiency", 0.845605188, ...
    "mass_flow_evidence", ...
        "conditional mean of Table 5.2 energy-balance inversions", ...
    "efficiency_evidence", ...
        "conditional Table 5.2 T/P plus HeXe-property inversion");
end

function out = evaluateCurrent(c, t1, t2, target, requiredSpeeds)
speedRatio = target.speed_rpm / c.N_design;
flowRatio = target.compressor_mass_flow_kg_s / c.mdot_design;
design = struct( ...
    "compressor_pressure_ratio", interp2(c.m_ratio_bp, c.speed_bp, ...
        c.PR_table, flowRatio, speedRatio), ...
    "compressor_efficiency", interp2(c.m_ratio_bp, c.speed_bp, ...
        c.ETAT_table, flowRatio, speedRatio), ...
    "turbine_mass_flow_kg_s", interp2(t1.bp_speed, t1.bp_er, ...
        t1.table_mf, target.speed_rpm, target.turbine_pressure_ratio), ...
    "turbine_efficiency", interp2(t2.bp_speed, t2.bp_mf, ...
        t2.table_eff, target.speed_rpm, target.turbine_mass_flow_kg_s));
design.relative_errors = relativeErrors(design, target);
design.max_relative_error = max(struct2array(design.relative_errors));
physicalCompressorSpeeds = c.speed_bp(:).' * c.N_design;
domain = struct( ...
    "compressor_speed_min_rpm", min(physicalCompressorSpeeds), ...
    "compressor_speed_max_rpm", max(physicalCompressorSpeeds), ...
    "turbine_speed_min_rpm", min(t1.bp_speed), ...
    "turbine_speed_max_rpm", max(t1.bp_speed), ...
    "covers_all_required_speeds", all(requiredSpeeds >= ...
        max(min(physicalCompressorSpeeds), min(t1.bp_speed)) & ...
        requiredSpeeds <= min(max(physicalCompressorSpeeds), ...
        max(t1.bp_speed))));
out = struct( ...
    "compressor", struct( ...
        "pr_all_rows_strictly_decreasing", ...
            all(diff(c.PR_table, 1, 2) < 0, "all"), ...
        "pressure_ratio_min", min(c.PR_table, [], "all"), ...
        "pressure_ratio_max", max(c.PR_table, [], "all"), ...
        "efficiency_min", min(c.ETAT_table, [], "all"), ...
        "efficiency_max", max(c.ETAT_table, [], "all")), ...
    "turbine", struct( ...
        "mass_flow_min_kg_s", min(t1.table_mf, [], "all"), ...
        "mass_flow_max_kg_s", max(t1.table_mf, [], "all"), ...
        "efficiency_min", min(t2.table_eff, [], "all"), ...
        "efficiency_max", max(t2.table_eff, [], "all")), ...
    "design", design, "domain", domain);
end

function out = evaluateCandidate(c, target, requiredSpeeds)
design = struct( ...
    "compressor_pressure_ratio", interp2(c.mC_bp, c.N_bp, ...
        c.PRc_tbl, target.compressor_mass_flow_kg_s, target.speed_rpm), ...
    "compressor_efficiency", interp2(c.mC_bp, c.N_bp, ...
        c.etac_tbl, target.compressor_mass_flow_kg_s, target.speed_rpm), ...
    "turbine_mass_flow_kg_s", interp2(c.PRt_bp, c.N_bp, ...
        c.mT_tbl, target.turbine_pressure_ratio, target.speed_rpm), ...
    "turbine_efficiency", interp2(c.mT_bp, c.N_bp, ...
        c.etat_tbl, target.turbine_mass_flow_kg_s, target.speed_rpm));
design.relative_errors = relativeErrors(design, target);
design.max_relative_error = max(struct2array(design.relative_errors));
[~, designRow] = min(abs(c.N_bp - target.speed_rpm));
[~, peakIndex] = max(c.PRc_tbl(designRow, :));
domain = struct( ...
    "speed_min_rpm", min(c.N_bp), ...
    "speed_max_rpm", max(c.N_bp), ...
    "required_speed_coverage", requiredSpeeds >= min(c.N_bp) & ...
        requiredSpeeds <= max(c.N_bp), ...
    "covers_all_required_speeds", all(requiredSpeeds >= min(c.N_bp) & ...
        requiredSpeeds <= max(c.N_bp)));
out = struct( ...
    "compressor", struct( ...
        "design_row_speed_rpm", c.N_bp(designRow), ...
        "design_pr_peak_index", peakIndex, ...
        "design_has_interior_pr_peak", ...
            peakIndex > 1 && peakIndex < numel(c.mC_bp), ...
        "pressure_ratio_min", min(c.PRc_tbl, [], "all"), ...
        "pressure_ratio_max", max(c.PRc_tbl, [], "all"), ...
        "efficiency_min", min(c.etac_tbl, [], "all"), ...
        "efficiency_max", max(c.etac_tbl, [], "all")), ...
    "turbine", struct( ...
        "mass_flow_min_kg_s", min(c.mT_tbl, [], "all"), ...
        "mass_flow_max_kg_s", max(c.mT_tbl, [], "all"), ...
        "efficiency_min", min(c.etat_tbl, [], "all"), ...
        "efficiency_max", max(c.etat_tbl, [], "all")), ...
    "design", design, "domain", domain);
end

function errors = relativeErrors(value, target)
errors = struct( ...
    "compressor_pressure_ratio", abs(value.compressor_pressure_ratio - ...
        target.compressor_pressure_ratio) / target.compressor_pressure_ratio, ...
    "compressor_efficiency", abs(value.compressor_efficiency - ...
        target.compressor_efficiency) / target.compressor_efficiency, ...
    "turbine_mass_flow_kg_s", abs(value.turbine_mass_flow_kg_s - ...
        target.turbine_mass_flow_kg_s) / target.turbine_mass_flow_kg_s, ...
    "turbine_efficiency", abs(value.turbine_efficiency - ...
        target.turbine_efficiency) / target.turbine_efficiency);
end

function writeOutputs(out, current, candidateResult, candidate, compressor, ...
        turbineFlow, turbineEfficiency, outputDir)
jsonPath = fullfile(outputDir, "offline_map_audit.json");
writelines(jsonencode(out, "PrettyPrint", true), jsonPath);

metrics = ["compressor_pressure_ratio"; "compressor_efficiency"; ...
    "turbine_mass_flow_kg_s"; "turbine_efficiency"];
target = out.targets;
summary = table(metrics, ...
    [target.compressor_pressure_ratio; target.compressor_efficiency; ...
     target.turbine_mass_flow_kg_s; target.turbine_efficiency], ...
    [current.design.compressor_pressure_ratio; ...
     current.design.compressor_efficiency; ...
     current.design.turbine_mass_flow_kg_s; ...
     current.design.turbine_efficiency], ...
    [candidateResult.design.compressor_pressure_ratio; ...
     candidateResult.design.compressor_efficiency; ...
     candidateResult.design.turbine_mass_flow_kg_s; ...
     candidateResult.design.turbine_efficiency], ...
    VariableNames=["metric", "target", "current", "candidate"]);
writetable(summary, fullfile(outputDir, "offline_map_summary.csv"));

figureHandle = figure("Visible", "off", "Color", "white", ...
    "Position", [100 100 1280 760]);
cleanup = onCleanup(@() close(figureHandle)); %#ok<NASGU>
layout = tiledlayout(figureHandle, 2, 2, "TileSpacing", "compact");
title(layout, "Gate 1: current and recovered rotating-map evidence");

nexttile;
plot(compressor.m_ratio_bp, compressor.PR_table.'); grid on;
xlabel("m/m_{design}"); ylabel("compressor pressure ratio");
title("Current compressor: all speed rows");

nexttile;
selected = unique(arrayfun(@(speed) nearestIndex(candidate.N_bp, speed), ...
    out.required_speeds_rpm));
plot(candidate.mC_bp, candidate.PRc_tbl(selected, :).'); grid on;
xlabel("mass flow (kg/s)"); ylabel("compressor pressure ratio");
title("Recovered candidate compressor");

nexttile;
plot(turbineFlow.bp_er, turbineFlow.table_mf); hold on;
plot(candidate.PRt_bp, candidate.mT_tbl(selected, :).', "--"); grid on;
xlabel("turbine expansion ratio"); ylabel("mass flow (kg/s)");
title("Turbine flow maps");

nexttile;
plot(turbineEfficiency.bp_mf, turbineEfficiency.table_eff); hold on;
plot(candidate.mT_bp, candidate.etat_tbl(selected, :).', "--"); grid on;
xlabel("mass flow (kg/s)"); ylabel("turbine efficiency");
title("Turbine efficiency maps");

exportgraphics(figureHandle, ...
    fullfile(outputDir, "offline_map_comparison.png"), "Resolution", 150);
end

function index = nearestIndex(axisValues, query)
[~, index] = min(abs(axisValues - query));
end

function value = sourceIdentity(pathValue, repoRoot)
pathValue = canonicalPath(pathValue, true);
if startsWith(pathValue, repoRoot + filesep)
    relative = extractAfter(pathValue, strlength(repoRoot) + 1);
else
    relative = "";
end
info = dir(pathValue);
value = struct("repository_relative_path", relative, ...
    "absolute_path", pathValue, "bytes", info.bytes, ...
    "sha256", sha256File(pathValue));
end

function requireFields(value, names, label, identifier)
if nargin < 4
    identifier = "rotatingMap:InvalidCurrent";
end
missing = names(~isfield(value, cellstr(names)));
if ~isempty(missing)
    error(identifier, "%s is missing fields: %s", label, join(missing, ", "));
end
end

function assertFiniteNumeric(value, identifier, label)
if ~isnumeric(value) || isempty(value) || any(~isfinite(value), "all")
    error(identifier, "%s contains empty, nonnumeric, or nonfinite data.", label);
end
end

function value = sha256File(pathValue)
bytes = java.nio.file.Files.readAllBytes(java.nio.file.Paths.get( ...
    char(pathValue), javaArray("java.lang.String", 0)));
digest = java.security.MessageDigest.getInstance("SHA-256").digest(bytes);
value = string(lower(reshape(dec2hex( ...
    typecast(digest, "uint8"), 2).', 1, [])));
end

function value = canonicalPath(pathValue, mustExist)
file = java.io.File(char(pathValue));
if mustExist && ~file.exists()
    error("rotatingMap:MissingInput", "Required input does not exist: %s", ...
        pathValue);
end
value = string(file.getCanonicalPath());
end
