function result = build_rotating_map_candidate_bundles(repoRoot, outputDir)
%BUILD_ROTATING_MAP_CANDIDATE_BUNDLES Build fixed C0-C3 MAT bundles.
%   Only coordinate conversion and orientation conversion are permitted.
%   Lookup surface values are copied exactly; no smoothing or fitting occurs.

arguments
    repoRoot (1,1) string
    outputDir (1,1) string
end

repoRoot = canonicalPath(repoRoot, true);
outputDir = canonicalPath(outputDir, false);
if isfolder(outputDir) || isfile(outputDir)
    error("rotatingMap:OutputExists", ...
        "Candidate-bundle output already exists: %s", outputDir);
end

compressorPath = fullfile(repoRoot, "hexe_compressor_lookup.mat");
turbineFlowPath = fullfile(repoRoot, "turbine_table1.mat");
turbineEfficiencyPath = fullfile(repoRoot, "turbine_table2.mat");
candidatePath = fullfile(repoRoot, "data", "provenance", ...
    "rotating_machinery", "recovered_20260902", "source", ...
    "Xu2022_PaperStyle_Equivalent_Lookup.mat");
currentCompressor = load(compressorPath);
currentTurbineFlow = load(turbineFlowPath);
currentTurbineEfficiency = load(turbineEfficiencyPath);
candidate = load(candidatePath);
validateInputs(currentCompressor, currentTurbineFlow, ...
    currentTurbineEfficiency, candidate);

currentCompressorBundle = struct( ...
    "compressor_speed_bp", currentCompressor.speed_bp, ...
    "compressor_flow_bp", currentCompressor.m_ratio_bp, ...
    "compressor_pr_table", currentCompressor.PR_table, ...
    "compressor_eta_table", currentCompressor.ETAT_table);
candidateCompressorBundle = struct( ...
    "compressor_speed_bp", candidate.N_bp / 55090, ...
    "compressor_flow_bp", candidate.mC_bp / 12.04, ...
    "compressor_pr_table", candidate.PRc_tbl, ...
    "compressor_eta_table", candidate.etac_tbl);
currentTurbineBundle = struct( ...
    "turbine_er_bp", currentTurbineFlow.bp_er(:), ...
    "turbine_speed_bp", currentTurbineFlow.bp_speed(:), ...
    "turbine_flow_table", currentTurbineFlow.table_mf, ...
    "turbine_mf_bp", currentTurbineEfficiency.bp_mf(:), ...
    "turbine_eta_table", currentTurbineEfficiency.table_eff);
candidateTurbineBundle = struct( ...
    "turbine_er_bp", candidate.PRt_bp(:), ...
    "turbine_speed_bp", candidate.N_bp(:), ...
    "turbine_flow_table", candidate.mT_tbl.', ...
    "turbine_mf_bp", candidate.mT_bp(:), ...
    "turbine_eta_table", candidate.etat_tbl.');

definitions = { ...
    "C0", "current", "current", currentCompressorBundle, currentTurbineBundle; ...
    "C1", "recovered_candidate", "current", candidateCompressorBundle, currentTurbineBundle; ...
    "C2", "current", "recovered_candidate", currentCompressorBundle, candidateTurbineBundle; ...
    "C3", "recovered_candidate", "recovered_candidate", candidateCompressorBundle, candidateTurbineBundle};

mkdir(outputDir);
try
    cases = struct([]);
    for index = 1:size(definitions, 1)
        caseId = definitions{index, 1};
        compressorSource = definitions{index, 2};
        turbineSource = definitions{index, 3};
        bundle = definitions{index, 4};
        turbineBundle = definitions{index, 5};
        names = fieldnames(turbineBundle);
        for fieldIndex = 1:numel(names)
            bundle.(names{fieldIndex}) = turbineBundle.(names{fieldIndex});
        end
        bundle.bundle_contract = contract(caseId, compressorSource, ...
            turbineSource);
        bundlePath = fullfile(outputDir, caseId + "_lookup.mat");
        save(bundlePath, "-struct", "bundle", "-v7");
        record = struct( ...
            "case_id", caseId, ...
            "compressor_source", compressorSource, ...
            "turbine_source", turbineSource, ...
            "bundle_repository_path", relativePath(bundlePath, repoRoot), ...
            "bundle_absolute_path", bundlePath, ...
            "bundle_sha256", sha256File(bundlePath), ...
            "bundle_bytes", dir(bundlePath).bytes);
        if index == 1
            cases = record;
        else
            cases(end + 1) = record; %#ok<AGROW>
        end
    end
    result = struct( ...
        "schema", "rotating_map_candidate_bundles_v1", ...
        "case_order", ["C0", "C1", "C2", "C3"], ...
        "source_hashes", struct( ...
            "current_compressor", sha256File(compressorPath), ...
            "current_turbine_flow", sha256File(turbineFlowPath), ...
            "current_turbine_efficiency", ...
                sha256File(turbineEfficiencyPath), ...
            "recovered_candidate", sha256File(candidatePath)), ...
        "coordinate_conversion", struct( ...
            "compressor_speed", "N_rpm/55090", ...
            "compressor_flow", "mass_flow_kg_s/12.04", ...
            "turbine", "physical axes unchanged; arrays transposed only for Simulink table orientation"), ...
        "surface_smoothed", false, ...
        "parameter_fitted", false, ...
        "formal_promotion", false, ...
        "cases", cases);
    writelines(jsonencode(result, "PrettyPrint", true), ...
        fullfile(outputDir, "bundle_manifest.json"));
catch exception
    if isfolder(outputDir)
        rmdir(outputDir, "s");
    end
    rethrow(exception)
end
end

function value = contract(caseId, compressorSource, turbineSource)
value = struct( ...
    "schema", "rotating_map_case_lookup_v1", ...
    "case_id", caseId, ...
    "compressor_source", compressorSource, ...
    "turbine_source", turbineSource, ...
    "compressor_input_order", ...
        ["normalized_speed", "normalized_mass_flow"], ...
    "compressor_speed_conversion", "N_rpm/55090", ...
    "compressor_flow_conversion", "mass_flow_kg_s/12.04", ...
    "turbine_flow_input_order", ["expansion_ratio", "speed_rpm"], ...
    "turbine_efficiency_input_order", ...
        ["mass_flow_kg_s", "speed_rpm"], ...
    "surface_smoothed", false, ...
    "parameter_fitted", false, ...
    "formal_promotion", false);
end

function validateInputs(c, t1, t2, candidate)
if ~isequal(size(c.PR_table), [numel(c.speed_bp), numel(c.m_ratio_bp)]) || ...
        ~isequal(size(c.ETAT_table), size(c.PR_table)) || ...
        ~isequal(size(t1.table_mf), [numel(t1.bp_er), numel(t1.bp_speed)]) || ...
        ~isequal(size(t2.table_eff), [numel(t2.bp_mf), numel(t2.bp_speed)]) || ...
        ~isequal(size(candidate.PRc_tbl), ...
            [numel(candidate.N_bp), numel(candidate.mC_bp)]) || ...
        ~isequal(size(candidate.etac_tbl), size(candidate.PRc_tbl)) || ...
        ~isequal(size(candidate.mT_tbl), ...
            [numel(candidate.N_bp), numel(candidate.PRt_bp)]) || ...
        ~isequal(size(candidate.etat_tbl), ...
            [numel(candidate.N_bp), numel(candidate.mT_bp)])
    error("rotatingMap:InvalidBundleSource", ...
        "One or more source arrays have an incompatible orientation.");
end
allValues = [c.PR_table(:); c.ETAT_table(:); t1.table_mf(:); ...
    t2.table_eff(:); candidate.PRc_tbl(:); candidate.etac_tbl(:); ...
    candidate.mT_tbl(:); candidate.etat_tbl(:)];
if any(~isfinite(allValues))
    error("rotatingMap:InvalidBundleSource", ...
        "A source lookup surface contains nonfinite values.");
end
end

function value = relativePath(pathValue, repoRoot)
pathValue = canonicalPath(pathValue, true);
if ~startsWith(pathValue, repoRoot + filesep)
    error("rotatingMap:PathOutsideRepository", ...
        "Bundle path escaped the repository root.");
end
value = extractAfter(pathValue, strlength(repoRoot) + 1);
end

function value = sha256File(pathValue)
bytes = java.nio.file.Files.readAllBytes(java.nio.file.Paths.get( ...
    char(pathValue), javaArray("java.lang.String", 0)));
digest = java.security.MessageDigest.getInstance("SHA-256").digest(bytes);
value = string(lower(reshape(dec2hex( ...
    typecast(digest, "uint8"), 2).', 1, [])));
end

function value = canonicalPath(pathValue, mustExist)
file = java.io.File(char(pathValue));
if mustExist && ~file.exists()
    error("rotatingMap:MissingInput", "Required input does not exist: %s", ...
        pathValue);
end
value = string(file.getCanonicalPath());
end
