function result = create_rotating_map_candidate_models( ...
        repoRoot, bundleDir, outputDir)
%CREATE_ROTATING_MAP_CANDIDATE_MODELS API-patch four temporary model copies.
%   All SLX writes are performed by Simulink load_system/set_param/
%   save_system.  The function does not simulate and never writes the source
%   model or root lookup MAT files.

arguments
    repoRoot (1,1) string
    bundleDir (1,1) string
    outputDir (1,1) string
end

SOURCE_SHA256 = ...
    "31745b6487234b64938f9b61131910599db75a1b53e3d1099b8585d0b7b4e8aa";
repoRoot = canonicalPath(repoRoot, true);
bundleDir = canonicalPath(bundleDir, true);
outputDir = canonicalPath(outputDir, false);
sourcePath = fullfile(repoRoot, "final_steady_24a.slx");
if sha256File(sourcePath) ~= SOURCE_SHA256
    error("rotatingMap:SourceHashMismatch", ...
        "The formal steady model no longer matches the approved source.");
end
if isfolder(outputDir) || isfile(outputDir)
    error("rotatingMap:OutputExists", ...
        "Candidate-model output already exists: %s", outputDir);
end
bundleManifest = fullfile(bundleDir, "bundle_manifest.json");
if ~isfile(bundleManifest)
    error("rotatingMap:MissingBundleManifest", ...
        "Missing C0-C3 bundle manifest.");
end

loadRuntimeInputs(repoRoot);
sourceContract = readModelContract(sourcePath);
mkdir(outputDir);
try
    cases = struct([]);
    for caseId = ["C0", "C1", "C2", "C3"]
        bundlePath = fullfile(bundleDir, caseId + "_lookup.mat");
        if ~isfile(bundlePath)
            error("rotatingMap:MissingBundle", ...
                "Missing lookup bundle for %s.", caseId);
        end
        bundle = load(bundlePath);
        validateBundle(bundle, caseId);
        assignBundleToBase(bundle);
        candidatePath = fullfile(outputDir, caseId + "_model.slx");
        createApiCopy(sourcePath, candidatePath, caseId);
        candidateContract = readModelContract(candidatePath);
        [changes, exactChanges] = compareDialogs( ...
            sourceContract.dialog_parameters, ...
            candidateContract.dialog_parameters);
        blockUnchanged = isequal(sourceContract.blocks, ...
            candidateContract.blocks);
        topologyUnchanged = isequal(sourceContract.edges, ...
            candidateContract.edges);
        solverUnchanged = isequal(sourceContract.solver, ...
            candidateContract.solver);
        if ~blockUnchanged || ~topologyUnchanged || ~solverUnchanged || ...
                ~exactChanges
            error("rotatingMap:CandidateContractViolation", ...
                "Candidate %s changed content outside four lookup blocks.", ...
                caseId);
        end
        record = struct( ...
            "case_id", caseId, ...
            "model_repository_path", relativePath(candidatePath, repoRoot), ...
            "model_absolute_path", candidatePath, ...
            "model_sha256", sha256File(candidatePath), ...
            "bundle_repository_path", relativePath(bundlePath, repoRoot), ...
            "bundle_sha256", sha256File(bundlePath), ...
            "changed_parameter_count", numel(changes), ...
            "changes", changes, ...
            "block_inventory_unchanged", blockUnchanged, ...
            "topology_unchanged", topologyUnchanged, ...
            "solver_unchanged", solverUnchanged, ...
            "update_diagram_passed", true, ...
            "simulation_call_count", 0, ...
            "formal_promotion", false);
        if isempty(cases)
            cases = record;
        else
            cases(end + 1) = record; %#ok<AGROW>
        end
    end
    result = struct( ...
        "schema", "rotating_map_candidate_models_v1", ...
        "source_repository_path", relativePath(sourcePath, repoRoot), ...
        "source_sha256", SOURCE_SHA256, ...
        "bundle_manifest_repository_path", ...
            relativePath(bundleManifest, repoRoot), ...
        "bundle_manifest_sha256", sha256File(bundleManifest), ...
        "cases", cases, ...
        "simulation_call_count", 0, ...
        "formal_promotion", false);
    writelines(jsonencode(result, "PrettyPrint", true), ...
        fullfile(outputDir, "model_manifest.json"));
catch exception
    closeAllCandidates();
    if bdIsLoaded("final_steady_24a")
        close_system("final_steady_24a", 0);
    end
    if isfolder(outputDir)
        rmdir(outputDir, "s");
    end
    rethrow(exception)
end
end

function createApiCopy(sourcePath, candidatePath, caseId)
sourceModel = "final_steady_24a";
candidateModel = caseId + "_model";
if bdIsLoaded(sourceModel) || bdIsLoaded(candidateModel)
    error("rotatingMap:ModelAlreadyLoaded", ...
        "Refusing to overwrite an already-loaded model namespace.");
end
load_system(sourcePath);
sourceCleanup = onCleanup(@() closeIfLoaded(sourceModel)); %#ok<NASGU>
save_system(sourceModel, candidatePath);
close_system(sourceModel, 0);
clear sourceCleanup

load_system(candidatePath);
candidateCleanup = onCleanup(@() closeIfLoaded(candidateModel)); %#ok<NASGU>
blocks = lookupBlocks(candidateModel);
set_param(blocks.compressor_efficiency, ...
    "BreakpointsForDimension1", "compressor_speed_bp", ...
    "BreakpointsForDimension2", "compressor_flow_bp", ...
    "Table", "compressor_eta_table");
set_param(blocks.compressor_pressure_ratio, ...
    "BreakpointsForDimension1", "compressor_speed_bp", ...
    "BreakpointsForDimension2", "compressor_flow_bp", ...
    "Table", "compressor_pr_table");
set_param(blocks.turbine_flow, ...
    "BreakpointsForDimension1", "turbine_er_bp", ...
    "BreakpointsForDimension2", "turbine_speed_bp", ...
    "Table", "turbine_flow_table");
set_param(blocks.turbine_efficiency, ...
    "BreakpointsForDimension1", "turbine_mf_bp", ...
    "BreakpointsForDimension2", "turbine_speed_bp", ...
    "Table", "turbine_eta_table");
set_param(candidateModel, "SimulationCommand", "update");
save_system(candidateModel, candidatePath);
close_system(candidateModel, 0);
clear candidateCleanup
end

function blocks = lookupBlocks(model)
paths = string(find_system(model, "LookUnderMasks", "all", ...
    "FollowLinks", "on", "BlockType", "Lookup_n-D"));
blocks = struct( ...
    "compressor_efficiency", findByTable(paths, "ETAT_table"), ...
    "compressor_pressure_ratio", findByTable(paths, "PR_table"), ...
    "turbine_flow", findByTable(paths, "table_mf"), ...
    "turbine_efficiency", findByTable(paths, "table_eff"));
end

function pathValue = findByTable(paths, expression)
matches = strings(0, 1);
for index = 1:numel(paths)
    if string(get_param(paths(index), "Table")) == expression
        matches(end + 1, 1) = paths(index); %#ok<AGROW>
    end
end
if numel(matches) ~= 1
    error("rotatingMap:LookupIdentityMismatch", ...
        "Expected one lookup table with expression %s; found %d.", ...
        expression, numel(matches));
end
pathValue = matches;
end

function loadRuntimeInputs(repoRoot)
scriptPath = replace(fullfile(repoRoot, "start.m"), "'", "''");
evalin("base", "run('" + scriptPath + "')");
end

function assignBundleToBase(bundle)
names = ["compressor_speed_bp", "compressor_flow_bp", ...
    "compressor_pr_table", "compressor_eta_table", ...
    "turbine_er_bp", "turbine_speed_bp", "turbine_flow_table", ...
    "turbine_mf_bp", "turbine_eta_table"];
for name = names
    assignin("base", name, bundle.(name));
end
end

function validateBundle(bundle, caseId)
names = ["compressor_speed_bp", "compressor_flow_bp", ...
    "compressor_pr_table", "compressor_eta_table", ...
    "turbine_er_bp", "turbine_speed_bp", "turbine_flow_table", ...
    "turbine_mf_bp", "turbine_eta_table", "bundle_contract"];
if any(~isfield(bundle, cellstr(names))) || ...
        string(bundle.bundle_contract.case_id) ~= caseId
    error("rotatingMap:InvalidBundle", ...
        "Lookup bundle does not match case %s.", caseId);
end
if ~isequal(size(bundle.compressor_pr_table), ...
        [numel(bundle.compressor_speed_bp), ...
         numel(bundle.compressor_flow_bp)]) || ...
        ~isequal(size(bundle.compressor_eta_table), ...
            size(bundle.compressor_pr_table)) || ...
        ~isequal(size(bundle.turbine_flow_table), ...
            [numel(bundle.turbine_er_bp), ...
             numel(bundle.turbine_speed_bp)]) || ...
        ~isequal(size(bundle.turbine_eta_table), ...
            [numel(bundle.turbine_mf_bp), ...
             numel(bundle.turbine_speed_bp)])
    error("rotatingMap:InvalidBundle", ...
        "Lookup bundle axes and tables are inconsistent.");
end
end

function contract = readModelContract(modelPath)
[~, model] = fileparts(modelPath);
model = string(model);
if bdIsLoaded(model)
    error("rotatingMap:ModelAlreadyLoaded", ...
        "Model is already loaded: %s", model);
end
load_system(modelPath);
cleanup = onCleanup(@() closeIfLoaded(model)); %#ok<NASGU>
contract = struct( ...
    "blocks", blockSnapshot(model), ...
    "edges", edgeSnapshot(model), ...
    "dialog_parameters", dialogSnapshot(model), ...
    "solver", solverSnapshot(model));
close_system(model, 0);
clear cleanup
end

function blocks = blockSnapshot(model)
paths = sort(string(find_system(model, "LookUnderMasks", "all", ...
    "FollowLinks", "on", "Type", "Block")));
blocks = strings(numel(paths), 2);
for index = 1:numel(paths)
    blocks(index, :) = [relativeBlockPath(paths(index), model), ...
        string(get_param(paths(index), "BlockType"))];
end
end

function edges = edgeSnapshot(model)
lines = find_system(model, "LookUnderMasks", "all", ...
    "FollowLinks", "on", "FindAll", "on", "Type", "Line");
edges = strings(0, 4);
for lineIndex = 1:numel(lines)
    sourcePort = get_param(lines(lineIndex), "SrcPortHandle");
    destinationPorts = get_param(lines(lineIndex), "DstPortHandle");
    if isempty(sourcePort) || sourcePort == -1 || isempty(destinationPorts)
        continue
    end
    for destinationIndex = 1:numel(destinationPorts)
        destinationPort = destinationPorts(destinationIndex);
        if destinationPort == -1
            continue
        end
        edges(end + 1, :) = [ ... %#ok<AGROW>
            relativeBlockPath(get_param(sourcePort, "Parent"), model), ...
            string(get_param(sourcePort, "PortNumber")), ...
            relativeBlockPath(get_param(destinationPort, "Parent"), model), ...
            string(get_param(destinationPort, "PortNumber"))];
    end
end
edges = sortrows(edges, [1, 2, 3, 4]);
end

function records = dialogSnapshot(model)
paths = sort(string(find_system(model, "LookUnderMasks", "all", ...
    "FollowLinks", "on", "Type", "Block")));
records = strings(0, 4);
for blockIndex = 1:numel(paths)
    block = paths(blockIndex);
    dialog = get_param(block, "DialogParameters");
    if isempty(dialog)
        continue
    end
    names = sort(string(fieldnames(dialog)));
    for nameIndex = 1:numel(names)
        name = names(nameIndex);
        records(end + 1, :) = [ ... %#ok<AGROW>
            relativeBlockPath(block, model), ...
            string(get_param(block, "BlockType")), name, ...
            encodeValue(get_param(block, name))];
    end
end
records = sortrows(records, [1, 3, 2, 4]);
end

function records = solverSnapshot(model)
names = ["StartTime"; "StopTime"; "SolverName"; "SolverType"; ...
    "FixedStep"; "MaxStep"; "MinStep"; "InitialStep"; "MaxOrder"; ...
    "RelTol"; "AbsTol"; "AutoScaleAbsTol"; "Refine"; ...
    "NumberNewtonIterations"; "ShapePreserveControl"; ...
    "ZeroCrossControl"; "ZeroCrossAlgorithm"; "ZcThreshold"; ...
    "ConsecutiveZCsStepRelTol"; "MaxConsecutiveZCs"; "MaxZcPerStep"; ...
    "MaxZcBracketingIterations"; "EnableFixedStepZeroCrossing"; ...
    "MinStepSizeMsg"; "SolverPrmCheckMsg"; "AlgebraicLoopMsg"; ...
    "ArtificialAlgebraicLoopMsg"; "ConsistencyChecking"; "DaesscMode"; ...
    "ODENIntegrationMethod"; "ExtrapolationOrder"; ...
    "StateRefinementMethod"; "SolverJacobianMethodControl"; ...
    "SolverResetMethod"; "DecoupledContinuousIntegration"; ...
    "UseModelRefSolver"; "EnableMultiTasking"];
records = strings(numel(names), 2);
for index = 1:numel(names)
    records(index, :) = [names(index), ...
        encodeValue(get_param(model, names(index)))];
end
end

function [changes, exact] = compareDialogs(before, after)
if size(before, 1) ~= size(after, 1) || ...
        ~isequal(before(:, 1:3), after(:, 1:3))
    error("rotatingMap:DialogInventoryChanged", ...
        "Candidate dialog-parameter inventory changed.");
end
rows = find(before(:, 4) ~= after(:, 4));
changes = repmat(struct("relative_path", "", "block_type", "", ...
    "parameter", "", "old_expression", "", "new_expression", ""), ...
    numel(rows), 1);
for index = 1:numel(rows)
    row = rows(index);
    changes(index) = struct( ...
        "relative_path", before(row, 1), ...
        "block_type", before(row, 2), ...
        "parameter", before(row, 3), ...
        "old_expression", before(row, 4), ...
        "new_expression", after(row, 4));
end
allowedParameters = ["BreakpointsForDimension1", ...
    "BreakpointsForDimension2", "Table"];
allowedBlocks = ["TAC/Compressor/2-D Lookup" + newline + "Table1", ...
    "TAC/Compressor/2-D Lookup" + newline + "Table3", ...
    "TAC/Turbine/2-D Lookup" + newline + "Table", ...
    "TAC/Turbine/2-D Lookup" + newline + "Table1"];
exact = numel(rows) == 12 && ...
    all(ismember(string({changes.parameter}), allowedParameters)) && ...
    all(ismember(string({changes.relative_path}), allowedBlocks)) && ...
    numel(unique(string({changes.relative_path}))) == 4;
end

function value = relativeBlockPath(block, model)
prefix = model + "/";
block = string(block);
if ~startsWith(block, prefix)
    error("rotatingMap:UnexpectedBlockPath", ...
        "Block path is outside loaded model: %s", block);
end
value = extractAfter(block, strlength(prefix));
end

function value = encodeValue(raw)
try
    value = string(jsonencode(raw));
catch
    value = strtrim(string(evalc("disp(raw)")));
end
end

function value = relativePath(pathValue, repoRoot)
pathValue = canonicalPath(pathValue, true);
if ~startsWith(pathValue, repoRoot + filesep)
    error("rotatingMap:PathOutsideRepository", ...
        "Path escaped the repository root: %s", pathValue);
end
value = extractAfter(pathValue, strlength(repoRoot) + 1);
end

function value = sha256File(pathValue)
bytes = java.nio.file.Files.readAllBytes(java.nio.file.Paths.get( ...
    char(pathValue), javaArray("java.lang.String", 0)));
digest = java.security.MessageDigest.getInstance("SHA-256").digest(bytes);
value = string(lower(reshape(dec2hex( ...
    typecast(digest, "uint8"), 2).', 1, [])));
end

function value = canonicalPath(pathValue, mustExist)
file = java.io.File(char(pathValue));
if mustExist && ~file.exists()
    error("rotatingMap:MissingInput", "Required input does not exist: %s", ...
        pathValue);
end
value = string(file.getCanonicalPath());
end

function closeIfLoaded(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end

function closeAllCandidates()
for model = ["C0_model", "C1_model", "C2_model", "C3_model"]
    closeIfLoaded(model);
end
end
