function test_paper54_constants()
% Verify thesis literals and their explicitly documented consequences.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(root);
C = paper54_constants();

expectedPR = 1.551 / 0.658;
assert(abs(C.compressor.PR - expectedPR) < 10 * eps(expectedPR), ...
    'Table 5.2 compressor pressure-ratio calculation is inconsistent.');

expectedEta = 1000.21 / (2252.2 - 1231.6);
assert(abs(C.generator.eta_calculated - expectedEta) < ...
    10 * eps(expectedEta), ...
    'Table 5.2 electrical-to-shaft efficiency calculation is inconsistent.');

residual = C.turbine.power_W - C.compressor.power_W - ...
    C.generator.shaft_power_W;
assert(abs(residual) < 1e-6, ...
    'Table 5.2 shaft-side power residual is not zero.');

assert(abs(C.turbine.Tin_K - 1522.96) < 10 * eps(1522.96), ...
    'Table 5.2 turbine inlet temperature literal is missing or incorrect.');
assert(abs(C.turbine.Pin_Pa - 1.539e6) < 10 * eps(1.539e6), ...
    'Table 5.2 turbine inlet pressure literal is missing or incorrect.');
assert(abs(C.recuperator.hot_out_T_K - 663.63) < 10 * eps(663.63), ...
    'Table 5.2 recuperator hot outlet temperature literal is missing or incorrect.');
assert(abs(C.recuperator.cold_out_T_K - 1100.91) < 10 * eps(1100.91), ...
    'Table 5.2 recuperator cold outlet temperature literal is missing or incorrect.');
assert(abs(C.reactor.outlet_T_K - 1600) < 10 * eps(1600), ...
    'Table 5.2 reactor outlet temperature literal is missing or incorrect.');
assert(abs(C.cooler.cold_inlet_T_K - 360.10) < 10 * eps(360.10), ...
    'Table 5.2 cooler cold-side inlet temperature literal is incorrect.');
assert(abs(C.cooler.cold_out_T_K - 609.58) < 10 * eps(609.58), ...
    'Table 5.2 cooler cold-side outlet temperature literal is incorrect.');
assert(~isfield(C.cooler, 'hot_out_T_K') && ...
    ~isfield(C.cooler, 'hot_out_P_Pa') && ~isfield(C.cooler, 'cold_out_P_Pa'), ...
    'Do not invent cooler outlet pressures not published in Table 5.2.');
end
