function test_solve_paper52_operating_point()
% Verify the solver's auditable report contract without claiming convergence.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(root);
report = solve_paper52_operating_point('DryRun', true, 'Save', false);
scaledReport = solve_paper52_operating_point('DryRun', true, 'Save', false, ...
    'OptimizerType', 'lsqnonlin', 'ScaleProblem', 'jacobian');

required = {'states', 'state_derivatives', 'state_blocks', ...
    'compressor', 'turbine', 'power', 'constraints', 'verified', ...
    'formal_file_created'};
for k = 1:numel(required)
    assert(isfield(report, required{k}), ...
        'Steady-state report is missing field: %s', required{k});
end

assert(numel(report.states) == 42, ...
    'The current model must export all 42 continuous states.');
assert(numel(report.state_derivatives) == 42, ...
    'The report must export one derivative for every continuous state.');
assert(numel(report.state_blocks) == 42, ...
    'The report must retain the exact state block path for every state.');
assert(report.output_constraints_count >= 8, ...
    'The trim specification must include the published Table 5.2 component boundaries.');
assert(report.constraints.N_rpm == 55090, ...
    'The operating-point speed constraint must be the Table 5.2 speed.');
assert(report.constraints.Pelectric_W == 1000.21e3, ...
    'The operating-point load constraint must be the Table 5.2 electrical power.');
assert(~report.verified, ...
    'A dry-run inventory must not be reported as a verified operating point.');
assert(~report.formal_file_created, ...
    'A dry run must not create the formal operating-point MAT file.');
assert(strcmp(scaledReport.options.optimizer_type, 'lsqnonlin'), ...
    'The solver must report the selected optimizer explicitly.');
assert(strcmp(scaledReport.options.scale_problem, 'jacobian'), ...
    'The solver must report the selected numerical scaling explicitly.');
end
